import json

with open('C:/Code/vinhlong360/web/data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_ids = {e['id'] for e in data.get('entities', [])}
before_count = len(data['entities'])

new_itineraries_raw = [
  {
    'id': 'itinerary-1day-vl-solo-budget',
    'title': 'Vinh Long 1 ngay Solo Budget 200k',
    'profile': 'solo backpacker',
    'duration': '1 ngay',
    'provinces': ['Vinh Long'],
    'season': 'bat ky',
    'summary': 'Lich trinh 1 ngay solo budget duoi 200k tai Vinh Long: cho noi sang som, Con Phu Da bang xe dap, Van Thanh Mieu, Bao tang tinh, bo ke song Long Ho. Tong chi phi ~225-275k tuy lua chon, kem lich mua, tips mac ca va packing list thuc te.',
    'content': 'Ngay 1: 05:00 Thue xe dap ben pha Vinh Long (50k/ngay), 05:30 Cho noi Cai Be nhin tu be, 07:00 Bua sang bun ca (25k), 08:00 Con Phu Da dap xe vuon trai cay (mien phi), 11:00 Ve ben, an com dia (35k), 13:00 Van Thanh Mieu, 14:30 Bao tang tinh Vinh Long (10k), 16:00 Bo ke song Long Ho, 18:00 An toi cha ca Long Xuyen (40k), 19:30 Ve nha.',
    'budget': 'Di chuyen 40k | Do+pha 45k | Xe dap con 50k | An sang 30k | Ca phe 15k | An trua 40k | Vao cua 10k | An nhe 25k | Du phong 20k = ~275k',
    'total_cost': '225.000d - 275.000d (co the duoi 200k neu bo thue xe dap va tu mang nuoc)',
    'packing': ['Binh nuoc loc ca nhan', 'Kem chong nang SPF 50+', 'Ao mua mong gap gon', 'Dep sandal chong nuoc hoac dep lao', 'Tien mat (cho va ben pha khong nhan chuyen khoan)', 'Tui zip chong nuoc cho dien thoai', 'Khan mat nho', 'Bang keo ca nhan phong ngua phong chan khi di bo', 'Sac du phong', 'CMND/ID'],
    'rainy_plan': 'Thay cho noi va con bang Bao tang tinh Vinh Long tu sang som; nghi mua tai Co.opmart hoac ca phe may lanh duong Pham Thai Buong; chieu tanh mua moi ra bo ke song Long Ho.',
    'mistakes': ['Thue tau lon xem cho noi buoi chieu - cho hop 5h-8h sang, chieu la bo lo hoan toan', 'Dat tour online gia cao 400-600k trong khi tu di duoc voi 200k', 'Quen mac ca tai ben pha - gia thuc thap hon gia het 30-50%', 'Mang giay da hoac sneaker trang - con dat uot, lay, can dep sandal', 'Khong an sang som - quan ngon nhat dong nhat 6h-8h, 9h nhieu cho da het'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-1day-bt-couple',
    'title': 'Ben Tre 1 ngay tu TP.HCM - Cap doi',
    'profile': 'cap doi',
    'duration': '1 ngay',
    'provinces': ['Ben Tre'],
    'season': 'mua kho',
    'summary': 'Lich trinh 1 ngay Ben Tre cho cap doi tu TP.HCM, ngan sach ~585k/nguoi, mua kho. Bao gom: xuong ba la kenh rach, vuon dua Con Phung, lang nghe keo dua, vuon cacao Cai Mon, am thuc dac san. Co phuong an mua, tips cap doi va packing list chi tiet.',
    'content': 'Ngay 1: 06:00 Xe khach tu BX Mien Tay (80k), 08:30 Den Ben Tre, thue xe may, 09:00 Con Phung - xuong ba la kenh rach (150k/nguoi), 12:00 An trua dac san (160k/cap), 14:00 Lang nghe keo dua Mo Cay, 15:30 Vuon cacao Cai Mon (50k), 17:00 Mua qua keo dua ve (100k), 18:00 Xe ve HCM.',
    'budget': 'Xe khach khu hoi 80k + an sang 45k + tour xuong 150k + an trua 160k + vuon cacao 50k + qua 100k = ~585k/nguoi',
    'total_cost': '~585.000d/nguoi (nam trong bien 400-600k)',
    'packing': ['Kem chong nang SPF50+ va ao chong nang dai tay 2 bo', 'Giay sandal de bam (di xuong, bo dat tron)', 'Tui zip chong nuoc dung dien thoai', 'Tien mat ~700.000d/nguoi', 'Ao mua mong bo tui', 'Binh nuoc 500ml', 'Mu vanh rong hoac non la (~30.000d tai cho)'],
    'rainy_plan': 'Bo xuong ngoai troi, thay bang nha may keo dua co mai che; thay vuon cacao bang Bao tang Ben Tre mien phi; an trua som trong phong may lanh; mua sam cho trong nha',
    'mistakes': ['Khong dat tour xuong truoc - cuoi tuan het cho', 'Di trua moi xuat phat - den noi nang gat', 'Khong mac ao chong nang khi ngoi xuong 2 tieng', 'Mang it tien mat - nhieu noi khong nhan chuyen khoan', 'Quen mang repellent muoi buoi chieu toi'],
    'quality_score': 7.7
  },
  {
    'id': 'itinerary-1day-tv-culture',
    'title': 'Tra Vinh 1 ngay Van hoa Khmer',
    'profile': 'du lich van hoa',
    'duration': '1 ngay',
    'provinces': ['Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh du lich van hoa Khmer Tra Vinh 1 ngay, ngan sach ~335k, bao gom chua Ang, Ao Ba Om, Bao tang Khmer, Chua Hang, Lang Ca Hom va cac goi y am thuc dac san dia phuong.',
    'content': 'Ngay 1: 06:00 Thue xe may (100k), 06:30 Chua Ang Pagoda - nghi le sang som, 08:00 Ao Ba Om - ao thieu thieng, 09:30 Bao tang Van hoa Dan toc Khmer (10k), 11:00 An banh canh Ben Co (25k), 12:30 Chua Hang - ba tang cap trang tri, 14:00 Lang det chieu Ca Hom, 16:00 Cho Tra Vinh mua trai cay - thot not, 17:30 An bun nuoc leo (30k), 18:30 Ve khach san.',
    'budget': 'Thue xe may 100k + xang 30k + vao cua 10k + an sang 35k + an trua 50k + nuoc uong 30k + mua sam 80k = 335k',
    'total_cost': '~335.000 VND (trong ngan sach 300-500k)',
    'packing': ['Ao dai tay hoac ao co co (vao chua)', 'Quan dai hoac vay dai qua goi', 'Giay dep de thao', 'Kem chong nang SPF 50+', 'Mu rong vanh', 'Khan lau mo hoi nho', 'Tien mat le (to 10k-50k)', 'Binh nuoc 500ml tai su dung', 'Sac du phong cho dien thoai/may anh'],
    'rainy_plan': 'Bo Lang Ca Hom (duong dat tron), tap trung buoi sang 06:00-11:00 tai Chua Ang, Ao Ba Om, Bao tang Khmer. Chua Hang va Chua Nodol van tham duoc vi co mai lon. Mua mien Tay thuong do buoi chieu.',
    'mistakes': ['Mac quan dui/ao ho vao chanh dien - bi tu choi hoac phai mac ao muon', 'Chup anh su tang khong xin phep - vi pham van hoa', 'Den Ao Ba Om luc 10-11 gio - nang choi mat cam giac thieng lieng', 'Khong mang tien le - chua va lang nghe khong thoi tien lon', 'Bo qua bun nuoc leo mam bo hoc vi ngai mui - day la trai nghiem am thuc Khmer chinh goc'],
    'quality_score': 8.3
  },
  {
    'id': 'itinerary-2day-vl-family-culo',
    'title': 'Vinh Long 2 ngay Gia dinh cu lao',
    'profile': 'gia dinh 2 tre em',
    'duration': '2 ngay 1 dem',
    'provinces': ['Vinh Long'],
    'season': 'mua kho',
    'summary': 'Lich trinh 2 ngay 1 dem kham pha cu lao Vinh Long cho gia dinh 2 tre em, ngan sach 500-675k/nguoi, mua kho.',
    'content': 'Ngay 1: 07:00 Xe tu HCM, 10:30 Den Vinh Long, an com tam, 12:00 Qua pha vao Con Phu Da, 12:30 Nhan phong homestay tren cu lao, 14:00 Dap xe vuon trai cay (xe doi + ghe con 120k/ngay), 16:30 Xuong nho tren kenh, 18:00 An toi homestay (com gia dinh 80k/nguoi), 19:30 Nghi dem. Ngay 2: 06:00 Cho noi (thue thuyen 250k-350k/thuyen), 08:30 Ve homestay an sang, 10:00 Tra phong - mua dac san, 11:30 Qua pha ve dat lien, 12:30 Ve HCM.',
    'budget': 'Xe khach 280-320k, pha 20k, xe dap 120k, vuon trai cay 160-200k, xuong 100-150k, thuyen cho noi 250-350k, an uong 2 ngay 700-900k, luu tru 350-500k, qua 100-200k',
    'total_cost': '2.1-2.7 trieu/gia dinh 4 nguoi (~500-675k/nguoi)',
    'packing': ['Quan ao thoang mat mau toi (2 bo/nguoi)', 'Dep quai hau chong tron', 'Kem chong nang SPF50+', 'Mu rong vanh cho ca tre em', 'Phao boi co tay hoac ao phao tre em', 'Tui zip chong nuoc cho dien thoai va vi', 'Thuoc say tau xe neu tre de say', 'Snack kho va 1-2 chai nuoc', 'Tien mat toi thieu 1.5 trieu/gia dinh', 'May anh hoac dien thoai sac day + pin du phong'],
    'rainy_plan': 'Thay dap xe bang xe om, tham quan lam keo dua/banh trang trong nha (~50k/nguoi), ghe Bao Tang Vinh Long (mien phi), o nha vuon an lau mam nghe mua',
    'mistakes': ['Den cho noi sau 08:00 - cho da tan', 'Khong dat homestay truoc - mua kho het phong som', 'Mac quan ao sang mau - de dinh bun va mau trai cay', 'Quen tien mat - ATM khong co tren dao', 'Khong hoi gia truoc khi len thuyen - de bi het gia', 'Cho tre di sandal tron - duong dat cu lao rat tron'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-2day-bt-eco',
    'title': 'Ben Tre 2 ngay Eco - Rung duoc & San chim',
    'profile': 'eco traveler',
    'duration': '2 ngay 1 dem',
    'provinces': ['Ben Tre'],
    'season': 'thang 9-3',
    'summary': 'Lich trinh 2 ngay 1 dem Ben Tre cho eco traveler: Ngay 1 kham pha rung ngap man Thanh Phu va vuon dua Mo Cay, Ngay 2 ngam chim tai San Chim Vam Ho. Tong chi phi uoc tinh 1-1.6 trieu/nguoi.',
    'content': 'Ngay 1: 07:00 Xe tu HCM (100k), 09:30 Den Ben Tre, an bun mam (30k), 10:30 Thue xe may (120k/ngay), 11:00 Rung ngap man Thanh Phu - thue xuong 2 gio (200-250k/thuyen), 13:30 Ve Mo Cay an trua (50k), 14:30 Vuon dua Mo Cay - ghe xuong dong goi (100k), 17:00 Nhan phong khach san Ben Tre (200-250k), 18:30 An toi (80k). Ngay 2: 05:00 Khoi dong xe may, 05:30 San Chim Vam Ho (30k ve), 06:00-08:00 Gio vang chim, thue thuyen vao sau (250k/thuyen 4 nguoi), 09:00 An sang bun moc (25k), 10:00 Di lang Cai Mon tham vuon cay, 12:30 Ve Ben Tre tra phong, 14:00 Xe ve HCM.',
    'budget': 'Xe khach 200k | Thuyen/xuong 200-250k | Di chuyen noi tinh 200-250k | Luu tru 250-350k | An uong 300-400k | Ve tham quan 30k | Thue xe dap 40k | Mua sam 50-80k',
    'total_cost': '1.27-1.6 trieu/nguoi (co the toi uu xuong duoi 1 trieu neu ghep nhom va chon cho o binh dan hon)',
    'packing': ['Ao dai tay chong nang/muoi (2 bo), mau toi/trung tinh', 'Thuoc chong muoi DEET 30%+', 'Dep sandal chong nuoc', 'Binh nuoc 1L tai su dung', 'Ong nhom (neu co) cho san chim', 'Kem chong nang SPF 50', 'Tui chong nuoc cho dien thoai', 'Tien mat (ATM o huyen le hiem)', 'Thuoc dau bung, tieu chay', 'Ao mua mong gap gon'],
    'rainy_plan': 'Ngay 1: Thay rung duoc bang Bao Tang Tinh (mien phi) + xuong keo dua Thanh Long (50k, co mai che). Ngay 2: Mua nhe van di san chim duoc, mang ao mua mong vi chim it bi xao tron hon.',
    'mistakes': ['Den san chim sau 08:00 - da het gio vang, chim bay di kiem an', 'Khong ghep nhom thue thuyen - di 1 minh ton gap 3-4 lan', 'Mac quan ao mau sang vao rung - lam dong vat hoang so', 'Khong mang thuoc chong muoi - rung ngap man muoi rat nhieu tu 16:00-19:00', 'Book nha nghi khong hoi truoc ve xe dap cho thue'],
    'quality_score': 7.7
  },
  {
    'id': 'itinerary-2day-tv-beach-temple',
    'title': 'Tra Vinh 2 ngay - Chua Khmer & Bien Ba Dong',
    'profile': 'cap doi',
    'duration': '2 ngay 1 dem',
    'provinces': ['Tra Vinh'],
    'season': 'thang 11-4',
    'summary': 'Lich trinh 2 ngay 1 dem Tra Vinh cho cap doi: Ngay 1 tham quan chua Khmer (Chua Ang, Chua Hang, Ao Ba Om), Ngay 2 bien Ba Dong. Ngan sach ~892k-1.2tr/nguoi.',
    'content': 'Ngay 1: 07:00 Xe khach tu HCM (120-150k), 09:30 Den Tra Vinh, an bun nuoc leo (30k), 10:30 Thue xe may (100k/ngay), 11:00 Chua Ang Pagoda (10k ve), 12:30 An com bui dia phuong (40k), 14:00 Ao Ba Om, 15:30 Chua Hang, 17:00 Quay ve TP Tra Vinh, nhan phong (175-250k), 18:30 An toi bun mam (40k). Ngay 2: 06:00 Tra phong, xe may di Ba Dong Beach (50km ~1.5h), 08:00 Bien Ba Dong - tam biet hoang, 11:00 An hai san tuoi (100k), 13:00 Quay ve TP.TV, 14:00 Xe khach ve HCM.',
    'budget': 'Xe khach 2 chieu: 240-300k/nguoi | Khach san: 175-250k/nguoi | An uong: 300-400k/nguoi | Xe may+xang+pha: ~100k/nguoi | Ve tham quan: 10k/nguoi | Dac san: 75-125k/nguoi',
    'total_cost': '892.000 - 1.192.000d/nguoi',
    'packing': ['CMND/CCCD', 'Kem chong nang SPF50+', 'Trang phuc kin dao du phong (ao khoan nhe vao chua)', 'Dep xo ngon de thao', 'Do boi + khan tam bien', 'Tui zip chong nuoc cho dien thoai', 'Tien mat (ATM chi o trung tam TP Tra Vinh)', 'Thuoc chong say xe', 'Binh nuoc ca nhan'],
    'rainy_plan': 'Neu mua ngay 2 (khong ra bien duoc): thay bang tham quan lang nghe dan lat My Long (Cau Ngang). Hoac ghe Vuon co Dang Van Duc o Don Chau xem hang ngan co trang bay ve chieu. Chi phi tuong duong, khong can tam bien.',
    'mistakes': ['Mac do ho khi vao chua Khmer - bi tu choi vao hoac phai muon khan quan', 'Di Ba Dong bang xe khach ma khong co xe may tai cho - bai bien rat dai, di bo rat met', 'Dat ve xe ve qua tre (sau 16h) - hay het cho dip cuoi tuan, nen book truoc online', 'Khong doi tien le truoc - cho va quan nho khong tra lai tien chan duoc', 'Bo qua nuoc thot not tuoi - day la thuc uong dac trung nhat Tra Vinh'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-2day-vl-photography',
    'title': 'Vinh Long 2 ngay Nhiep anh chuyen nghiep',
    'profile': 'nhiep anh gia',
    'duration': '2 ngay',
    'provinces': ['Vinh Long'],
    'season': 'thang 11-3',
    'summary': 'Lich trinh du lich Vinh Long 2 ngay chuyen sau cho nhiep anh gia, thang 11-3, ngan sach khong gioi han. Bao gom chi tiet theo gio, dia diem chup anh dep nhat (song Co Chien, Cu Lao An Binh, Cho noi, lang nghe truyen thong), goi y an uong va luu tru cu the, tong chi phi ~4.8 trieu/nguoi, tips chuyen mon cho nhiep anh gia.',
    'content': 'Ngay 1: 04:30 Ra ben pha chup golden hour song Co Chien, 06:00 Cho noi Cai Be (thue thuyen 400k/2h), 09:00 Ve khach san an sang, 10:00 Di bo lang Vinh Long xua, chup kien truc Phap, 12:30 An trua seafood (150k), 14:00 Cu Lao An Binh - xe dap lang nghe banh trang, gom Thu Hoa, 17:00 Golden hour song - chup panorama, 19:00 An toi nha hang view song, 20:30 Ve nghi. Ngay 2: 05:00 Sunrise chup lang gach Mang Thit, 09:00 Tham lang nghe gom Thu Hoa, 12:00 An trua (120k), 14:00 Chua Tien Chau - anh kien truc, 16:00 Chup long bridge Bo Ke ben song, 18:00 Ve nghi, xu ly anh.',
    'budget': 'Xuong thue 2 ngay: 400k | Do/ve: 200k | Xe dap + xe om: 300k | An uong 6 bua: 1.200k | Luu tru 2 dem khach san 4 sao: 2.400k | Linh tinh: 300k',
    'total_cost': '~4.800.000 VND / nguoi (2 ngay 2 dem)',
    'packing': ['May anh chinh + body du phong', 'Ong kinh 16-35mm (canh rong)', 'Ong kinh 70-200mm (chan dung xa)', 'Ong kinh 85mm f/1.4 (portrait)', 'Bo loc ND8, ND64, CPL (chong nguoc sang song nuoc)', 'Chan may carbon (nhe, chac)', 'Tui chong nuoc cho may anh', 'Pin du phong x3 + sac nhanh', 'The nho 256GB x2', 'Ao mua mong + mu rong vanh', 'Giay sandal chong nuoc', 'Kem chong nang SPF50+', 'Thuoc chong muoi (toi o kenh rach nhieu)'],
    'rainy_plan': 'Mua nhe: tiep tuc chup, mua tao mood dep cho anh lang que. Mua lon: Bao Tang Vinh Long (mien phi, 9h-17h) + Dinh Than Vinh Phuoc (kien truc co, anh den/bong toi) + Cafe River View chup nguoi qua cua so.',
    'mistakes': ['Den tre, bo lo golden hour sang som - nen o khach san gan ben, di bo ra', 'Khong mang du pin va the nho - VL it tiem anh chuyen nghiep', 'Chup vuon cay khong xin phep - bi duoi, mat thien cam nguoi dan', 'An o hang Tay/resort - bo qua am thuc dia phuong dac sac', 'Quen kem chong nang - song nuoc phan chieu nang gap doi'],
    'quality_score': 8.2
  },
  {
    'id': 'itinerary-2day-bt-luxury',
    'title': 'Ben Tre 2 ngay Luxury Resort',
    'profile': 'du lich cao cap',
    'duration': '2 ngay 1 dem',
    'provinces': ['Ben Tre'],
    'season': 'mua kho',
    'summary': 'Lich trinh 2 ngay 1 dem Ben Tre cao cap: Ngay 1 tham Con Phung bang thuyen rieng, spa tai Mekong Riverside Resort; Ngay 2 vuon trai cay Cai Mon mua kho. Tong chi phi 3.5-5.1 trieu/nguoi tuy nhom.',
    'content': 'Ngay 1: 07:00 Xe rieng tu HCM (700k/xe), 10:00 Check-in Mekong Riverside Resort (2.500k/dem), 11:00 Thuyen rieng tham Con Phung (400k/giuong), 13:00 An trua buffet resort (250k), 15:00 Spa cap doi (550k/2 nguoi), 17:30 Hoang hon song, 19:00 An toi nha hang resort (200k/nguoi). Ngay 2: 07:00 An sang resort, 09:00 Thue xe may (120k), 10:00 Vuon trai cay Cai Mon (50k ve), 12:00 An trua hai san (150k), 14:00 Mua keo dua tai xuong Thanh Long, 16:00 Tra phong, 17:00 Xe ve HCM.',
    'budget': 'Xe: 700k | Luu tru: 2.500k | An uong: 700k | Thuyen: 400k | Spa: 550k | Ve+qua: 250k = ~5.100k/nguoi (nhom 2). Nhom 4 con ~3.500-4.000k/nguoi.',
    'total_cost': '3.500.000-5.100.000d/nguoi (tuy nhom 2-4 nguoi)',
    'packing': ['Kem chong nang SPF50+, kinh mat phan cuc', 'Mu rong vanh', 'Ao nhe chong nang hoac khan lua mong', 'Giay sandal de bang chong tron', 'Tien mat ~500.000d menh gia nho', 'Tui ziplock cho dien thoai khi di thuyen', 'Thuoc chong say song (du phong)', 'Trang phuc toi mau de tham lang nghe banh trang - bot ban day'],
    'rainy_plan': 'Thay Vuon Cai Mon bang: Bao tang Ben Tre (trong nha, mien phi) + Xuong keo dua Thanh Long (co mai che) + Cooking class hoac thu gian ho boi trong nha tai resort.',
    'mistakes': ['Dat phong Garden View vi re hon, roi tiec khi thay Riverview', 'Di Con Phung vao cuoi tuan - dong tour doan, mat cam giac yen tinh', 'Khong dat spa truoc, den noi kin slot', 'Quen mang kem chong nang SPF50+ - tren song phan chieu UV rat manh', 'Mac quan ao sang mau di lang nghe banh trang - bot ban day'],
    'quality_score': 7.7
  },
  {
    'id': 'itinerary-3day-vl-bt-combo',
    'title': 'VL+BT 3 ngay - Cu lao & Dua',
    'profile': 'nhom ban 4-6 nguoi',
    'duration': '3 ngay 2 dem',
    'provinces': ['Vinh Long', 'Ben Tre'],
    'season': 'bat ky',
    'summary': 'Lich trinh 3 ngay 2 dem Vinh Long + Ben Tre cho nhom ban 4-6 nguoi, ngan sach 850k-1.1tr/nguoi. Ngay 1: Cu lao An Binh - dap xe vuon trai cay, chua Tien Chau. Ngay 2: Cho noi Cai Be + Ben Tre - Con Phung kayak, xuong keo dua. Ngay 3: Cu lao Minh + mua dac san ve.',
    'content': 'Ngay 1: 07:00 Xe khach tu HCM, 10:00 Den Vinh Long, qua pha (10k), nhan phong homestay Cu Lao An Binh, 12:00 An com gia dinh (50k), 14:00 Dap xe vuon (60k/ngay), 16:30 Chua Tien Chau, 18:30 An toi, uong ruou nep. Ngay 2: 05:30 Cho noi Cai Be (thuyen 200k), 08:30 Xe sang Ben Tre, 10:00 Con Phung kayak (150k/nguoi), 12:30 An trua + xuong keo dua (70k), 15:00 Lang nghe banh trang, 18:00 Nhan phong khach san. Ngay 3: 07:30 An sang bun, 09:00 Cu lao Minh qua pha, 11:00 Cho dac san, 13:00 Ve HCM.',
    'budget': 'Di chuyen: 300-400k | Luu tru 2 dem: 600-900k | An 3 ngay: 600-800k | Tour + tham quan: 250-400k | Mua sam: 100-200k | TONG: ~850k-1.1tr/nguoi',
    'total_cost': '850,000 - 1,100,000 VND/nguoi',
    'packing': ['Kem chong nang SPF50+, kinh mat, mu tai beo rong vanh', 'Ao mua poncho gap gon (khong can o)', 'Dep quai hau chong tron + dep leo dung trong nha', 'Quan short + ao thun thoang mat 2-3 bo', 'Tui zip chong nuoc dung dien thoai', 'Thuoc say tau xe, thuoc tieu chay, dau gio', 'Tien mat (ATM hiem o cu lao)', 'Sac du phong', 'Tui vai nho dung dac san'],
    'rainy_plan': 'Thay kayak/dap xe ngoai troi bang tham quan xuong keo dua co mai che va bao tang Ben Tre. Di ghe co mai che ngam mua tren song. Tranh cho noi Cai Be khi mua to. Buoi toi: uong ruou nep dua, choi bai tai homestay.',
    'mistakes': ['Den cho noi Cai Be sau 9h sang - cho da tan, phai day truoc 6h', 'Khong mac ca khi thue ghe le - gia cao gap doi, nen nho homestay dat giup', 'Mua keo dua tai diem du lich thay vi cho - dat hon 50-70%', 'Di dep le ra cu lao - duong dat uot tron, can dep quai hau', 'Khong dat truoc tour kayak/ghe cuoi tuan - het cho', 'Quen kem chong nang - song nuoc phan chieu UV rat manh'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-3day-bt-tv-culture',
    'title': 'BT+TV 3 ngay - Lich su & Khmer',
    'profile': 'du lich hoc thuat',
    'duration': '3 ngay 2 dem',
    'provinces': ['Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh 3 ngay 2 dem du lich hoc thuat Ben Tre + Tra Vinh, tap trung lich su khang chien va van hoa Khmer. Ngan sach 1.2-1.5tr/nguoi neu o ghep.',
    'content': 'Ngay 1 Ben Tre: 08:00 Khu luu niem Nguyen Thi Dinh (30k), 10:00 Di tich Dong Khoi Mo Cay (mien phi), 12:00 An bun ca kho Ben Tre, 14:00 Bao tang Ben Tre (15k), 16:30 Nhan phong. Ngay 2 Tra Vinh: 08:00 Xe sang TV (80k), 10:00 Chua Ang Pagoda, 11:30 Ao Ba Om (mien phi), 13:00 An banh canh Ben Co, 14:30 Bao tang Van hoa Khmer (15k), 16:30 Chua Hang, 18:00 Nhan phong. Ngay 3: 08:00 Lang det Ca Hom (mien phi), 10:30 Chua Nodol, 12:00 An bun nuoc leo, 14:00 Xe ve HCM.',
    'budget': '1.615-1.935k/nguoi day du. Tiet kiem con 1.2-1.5tr neu o ghep 3-4 nguoi/phong va an chay 1 ngay.',
    'total_cost': '1.200.000 - 1.500.000 VND/nguoi (o ghep)',
    'packing': ['Quan dai/vay dai (vao chua Khmer)', 'May ghi am nho hoac dien thoai co mic tot', 'So tay + but day', 'Tien mat menh gia nho (20k-50k)', 'Kem chong nang SPF50+', 'Ao mua poncho (khong phai o)', 'Google Maps offline tai san vung Ben Tre + Tra Vinh', 'Danh sach lien he bao tang da in san', 'Giay de bang (duong con/duong dat)', 'Thuoc chong say xe neu can'],
    'rainy_plan': 'Ngay 1 mua: thay Con Phung bang Xuong keo dua Thanh Long (mai che). Ngay 2 mua: thay Lang det Ca Hom bang Bao tang Van hoa Khmer Nam Bo tai DH Tra Vinh (lien he 0294 3855 246). Ngay 3 mua: o lai bao tang them 1-2 gio thay vi Chua Hang.',
    'mistakes': ['Khong dat truoc huong dan vien bao tang - tham quan ma khong co giai thich chuyen sau', 'Mac quan short vao chanh dien chua Khmer - bi tu choi vao', 'Khong tai Google Maps offline - lac duong tren duong nho mien Tay', 'Dat phong muon vao mua Ok Om Bok thang 10 am lich - het phong, gia gap doi', 'Quen mang tien mat nho - nhieu diem o Tra Vinh chua nhan chuyen khoan'],
    'quality_score': 7.7
  },
  {
    'id': 'itinerary-3day-tv-vl-reverse',
    'title': 'TV->VL 3 ngay nguoc dong',
    'profile': 'solo traveler',
    'duration': '3 ngay 2 dem',
    'provinces': ['Tra Vinh', 'Vinh Long'],
    'season': 'mua kho',
    'summary': 'Lich trinh 3 ngay 2 dem Tra Vinh -> Vinh Long danh cho solo traveler mua kho, ngan sach 850-1.290k tuy lua chon, chia gio cu the tu 05:30 den 14:00 ngay 3, gom chua Khmer, bien Ba Dong, con An Binh, lang gach Mang Thit.',
    'content': 'Ngay 1 Tra Vinh: 05:30 Chua Ang sang som (toan canh dep nhat), 07:00 An hu tieu Tra Vinh (25k), 08:00 Thue xe may (100k), 09:00 Ao Ba Om, 10:30 Chua Hang, 12:00 An banh canh Ben Co (30k), 13:30 Bao tang Khmer (10k), 15:00 Nhan phong, nghi. Ngay 2: 06:30 Xe may Ba Dong Beach (90km), 08:30 Bien Ba Dong biet hoang - tam, chup anh, 12:00 An hai san (100k), 14:00 Quay ve, 17:00 Xe khach sang Vinh Long (80k). Ngay 3 Vinh Long: 05:30 Cho noi Cai Be (200k thuyen), 08:30 An sang, 09:30 Cu Lao An Binh dap xe (60k), 12:00 An trua, 14:00 Lang gach Mang Thit, ve HCM.',
    'budget': 'Di chuyen ~480k | Luu tru ~220k | An uong ~470k | Tham quan ~120k | Tong ~1.290k. Tiet kiem con ~850-900k neu bo Ba Dong va chon phong quat.',
    'total_cost': '850k-1.290k/nguoi',
    'packing': ['Ao quan che khuat (cho chua Khmer)', 'Kem chong nang SPF50+', 'Ao mua mong gap duoc', 'Dep chong tron de cung', 'Binh nuoc giu lanh 500ml', 'Sac du phong', 'Tien mat le 200k trong tui rieng', 'Thuoc say xe', 'Khau trang hoac khan che mat', 'Tui zip bao ve dien thoai va passport'],
    'rainy_plan': 'Ngay 1: Bao tang Tra Vinh thay Ba Dong. Ngay 2: Cho noi van di duoc voi ao mua, mua to doi sang lang nghe keo dua trong nha. Ngay 3: Lang gach Mang Thit dep hon khi co may thap, giu nguyen lich.',
    'mistakes': ['Den cho noi luc 9-10h khi da tan tu 7h sang', 'Khong dat ve xe ve truoc, het cho chieu thu Sau', 'Mac ao ho vai vao chua Khmer bi tu choi', 'Quen kem chong nang khi di bai Ba Dong hoang so', 'Thue xe may khong co bang lai quoc te', 'Khong mang tien mat le, quan nho va xe om khong nhan the'],
    'quality_score': 8.3
  },
  {
    'id': 'itinerary-3day-family-senior',
    'title': '3 ngay Mien Tay - Nguoi cao tuoi',
    'profile': 'gia dinh co ong ba 60+',
    'duration': '3 ngay 2 dem',
    'provinces': ['Vinh Long', 'Ben Tre'],
    'season': 'thang 11-4',
    'summary': 'Lich trinh 3 ngay 2 dem tai Vinh Long va Ben Tre danh cho gia dinh co ong ba 60+, ngan sach 1-2 trieu/nguoi, chia theo gio cu the voi day du dia diem, an uong, luu tru, di chuyen, tips suc khoe va packing list.',
    'content': 'Ngay 1 Vinh Long: 07:30 Xe tu HCM, 10:30 Khach san 1 sao gan trung tam (200-250k), 12:00 An com gia dinh (60k/nguoi), 14:00 Van Thanh Mieu (mien phi, co ghe ngoi nhieu), 15:30 Bo ke song Long Ho, 17:30 An toi (80k), nghi som 21:00. Ngay 2 Ben Tre: 07:00 Xe sang Ben Tre (60k), 09:00 Con Phung (thuyen co mai - mat, khong say song, 150k), 11:30 An trua dac san (100k), 14:00 Xuong keo dua (co may lanh, ngoi nghi thoai mai), 16:00 Ve khach san (200k), nghi. Ngay 3: 07:00 Cho noi Cai Be (thuyen co mai 200k), 09:30 Ve Vinh Long, an sang, tra phong, 11:00 Xe ve HCM.',
    'budget': '1.700.000 - 2.500.000d/nguoi day du; duoi 1.500.000d neu ghep phong 3-4 nguoi',
    'total_cost': '1.500.000 - 2.500.000d/nguoi',
    'packing': ['Ao thun cotton thoang khi 2-3 bo', 'Ao khoan nhe chong nang', 'Giay de bang chong tron', 'Mu rong vanh + khan choang co', 'Kinh mat chong UV', 'Thuoc say xe + thuoc ca nhan (huyet ap, tieu duong)', 'Kem chong nang SPF 50+', 'Thuoc chong muoi xit hoac vong deo tay', 'Tui chong nuoc cho dien thoai', 'Tien mat le 500k-1tr', 'Sac du phong', 'Bang ca nhan + thuoc sat trung', 'Dau gio Eagle Brand'],
    'rainy_plan': 'Bo xuong cheo va cho noi, thay bang tham quan nha may keo dua Thanh Long (trong nha), Bao tang Ben Tre (mien phi, co mai che). Buoi toi xem don ca tai tu tai nha hang lon 19:00-21:00. Mua ao mua tien loi tai cho dia phuong 30.000d/cai neu mua nhe.',
    'mistakes': ['Di cho noi buoi chieu (cho hop 04:00-08:00)', 'Khong dat xe thue truoc mua le tet', 'An hai san via he khong ro nguon goc', 'Quen doi tien mat le cho vung nong thon', 'Mac trang phuc ho khi vao chua/nha co', 'Mac ao trang len xuong (de dinh bun)', 'Khong mang thuoc chong muoi (nhieu sau 17:00)'],
    'quality_score': 7.7
  },
  {
    'id': 'itinerary-4day-3province-loop',
    'title': '4 ngay 3 tinh vong lap day du',
    'profile': 'first-time visitor',
    'duration': '4 ngay 3 dem',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh 4 ngay 3 dem vong lap Vinh Long - Ben Tre - Tra Vinh cho first-time visitor, ngan sach 1-1.5 trieu/nguoi. Bao gom gio giac cu the, quan an, luu tru, chi phi chi tiet, lich mua, loi thuong gap va packing list.',
    'content': 'Ngay 1 Vinh Long: 07:00 Xe tu HCM, 10:00 Cho noi Cai Be (truoc), 11:30 Nhan phong, 13:00 Dap xe Cu Lao An Binh, 17:00 Van Thanh Mieu, 18:30 An toi bo song. Ngay 2 Ben Tre: 07:30 Xe sang Ben Tre, 09:00 Con Phung, 11:30 Xuong keo dua, 13:30 An trua, 15:00 Lang nghe banh trang, 17:00 Nhan phong. Ngay 3 Tra Vinh: 08:00 Xe sang TV, 10:00 Chua Ang, 11:30 Ao Ba Om, 13:00 An banh canh Ben Co, 14:30 Bao tang Khmer, 16:30 Chua Hang, 18:00 Nhan phong. Ngay 4: 07:00 Bien Ba Dong hoac Lang Ca Hom, 12:00 An trua, 14:00 Xe ve HCM.',
    'budget': 'Tong uoc tinh: 1.550.000-2.350.000d/nguoi (tiet kiem toi da: ~1.0-1.2 trieu khi di nhom, o ghep phong)',
    'total_cost': '1.0-1.5 trieu/nguoi (ngan sach tiet kiem, di nhom) | 1.5-2.35 trieu/nguoi (di doi)',
    'packing': ['Ao mua mong (bat buoc)', 'Kem chong nang SPF 50+', 'Quan dai hoac khan quang (vao chua)', 'Dep sandal chong tron', 'Kem chong muoi', 'Tui zip chong nuoc cho dien thoai va vi', 'Tien mat du dung cho 4 ngay'],
    'rainy_plan': 'Ngay 1: Bao tang Vinh Long + cho trai cay trong nha | Ngay 2: Bao tang Ben Tre + xuong keo dua | Ngay 3: Them chua Khmer + Bao tang Van hoa Khmer Tra Vinh (bo bien Ba Dong). Mua mien Tay thuong tanh sau 1-2 tieng, luon mang ao mua.',
    'mistakes': ['Vao chua Khmer mac quan dui, ao ba lo - bi tu choi hoac phai thue khan che', 'Khong hoi gia truoc khi len do/xe om - de bi tinh gap doi', 'Dat tour ghep 1 ngay 3 tinh - chay qua loa, khong trai nghiem thuc su', 'Mang hanh ly to - kho khi qua cu lao, duong nho', 'Khong chuan bi tien mat du - ATM thua o vung nong thon va cu lao'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-5day-honeymoon-deluxe',
    'title': 'Tuan trang mat 5 ngay Deluxe',
    'profile': 'cap doi trang mat',
    'duration': '5 ngay 4 dem',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'thang 11-4',
    'summary': 'Lich trinh du lich trang mat 5 ngay 4 dem tai Vinh Long, Ben Tre, Tra Vinh voi chi phi uoc tinh 4.700k-6.800k/nguoi, bao gom lich gio cu the, goi y an uong/luu tru, tips cap doi, lich thay the mua, loi thuong gap va packing list.',
    'content': 'Ngay 1 Vinh Long: Xe rieng tu HCM, Nhan phong resort, Chieu tham Cu Lao An Binh bang thuyen rieng, Toi an sunset dinner. Ngay 2 Ben Tre: Cho noi sang som, Chuyen sang Mekong Riverside Resort, Tham Con Phung bang sampan rieng, Spa cap doi. Ngay 3 Ben Tre: Vuon cacao Cai Mon, Lang keo dua Mo Cay, Toi cuoc di bo bo song. Ngay 4 Tra Vinh: Chua Ang sang soc, Ao Ba Om, Bien Ba Dong, Nhan phong khach san view bien. Ngay 5: Chua Hang, Cho Tra Vinh, Ve HCM.',
    'budget': 'Luu tru: 1.800k-2.600k | An uong: 1.500k-2.000k | Di chuyen: 800k-1.200k | Hoat dong: 300k-500k | Mua sam: 300k-500k',
    'total_cost': '4.700.000-6.800.000 VND/nguoi',
    'packing': ['Kem chong nang SPF 50+, kinh mat, mu rong vanh', 'Ao chong nang dai tay (bat buoc tren song)', 'Sandal chong nuoc + dep lao', 'Khan quang/vai che vai (vao chua)', 'Thuoc say tau, thuoc tieu hoa, dau gio', 'Tui chong nuoc cho dien thoai/may anh', 'Tien mat du (ATM it o vung nong thon)', 'Binh nuoc ca nhan', 'Quan ao nhe, thoang, mau sang (28-34 do C)', 'Power bank'],
    'rainy_plan': 'Hoc nau an tai resort, massage cap doi, tham quan bao tang va chua Khmer co mai che tai Tra Vinh, xem phim tai phong.',
    'mistakes': ['Len lich qua day - mien Tay di lai cham, co cau pha mat thoi gian', 'Khong dat xuong/thuyen truoc - mua cao diem thieu phuong tien', 'Mac vay ngan vao chua Khmer - bi tu choi vao', 'Quen kem chong nang - song nuoc phan chieu nang rat manh', 'Doi tien le khong du - nhieu cho va ben thuyen khong nhan chuyen khoan'],
    'quality_score': 8.3
  },
  {
    'id': 'itinerary-5day-foodie-tour',
    'title': '5 ngay Food Tour am thuc mien Tay',
    'profile': 'foodie / food blogger',
    'duration': '5 ngay 4 dem',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh 5 ngay Food Tour am thuc mien Tay (Vinh Long - Ben Tre - Tra Vinh), chia theo gio cu the, danh cho foodie/food blogger, ngan sach ~2.1tr/nguoi khi di 2 nguoi.',
    'content': 'Ngay 1 Vinh Long: An sang bun rieu oc Thien Huong, Cho noi xem hang nong san, Bua trua com mam don gian nha vuon, Chieu tham lang gach Mang Thit an banh canh, Toi lau man goi ruou nep dua. Ngay 2 Ben Tre: Sang som cho noi Ben Tre an bun mam, Xuong keo dua thu (an mau), Cai Mon an trai cay mua, Toi lau ca keo Mekong. Ngay 3 Ben Tre-Tra Vinh: Sang hu tieu lo chay Ben Tre, Chuyen sang TV, Trua banh canh Ben Co dac trung, Chieu cho TV thu banh Khmer. Ngay 4 Tra Vinh: Sang bun nuoc leo mam bo, An sang cho - bap chuoi ham, Toi com chay chua Ang (hoi truoc). Ngay 5: Mua banh trang me xung, keo dua ve, ve HCM.',
    'budget': '~2.1tr/nguoi (di 2 nguoi chia phong) hoac ~2.5tr/nguoi (di solo). Tong ca chuyen: ~3.65tr.',
    'total_cost': '3.650.000d cho 1 nguoi (solo) / ~4.200.000d cho 2 nguoi (chia doi ~2.100.000d/nguoi)',
    'packing': ['Tien mat le (500k menh gia 10k-50k)', 'May anh + o cung ngoai 500GB', 'Tui zip dung do an mua ve', 'Ao mua poncho (khong dung o khi di xe may)', 'Giay sandal chong nuoc', 'Binh nuoc ca nhan (tranh nhua)', 'So tay ghi ten quan + so dien thoai', 'Thuoc dau bung, men tieu hoa (an nhieu mon la)', 'Kem chong nang SPF 50+', 'Tui vai dung qua (tranh tui nilon)'],
    'rainy_plan': 'Thay vuon cay/cu lao -> ghe xuong san xuat trong nha (keo dua, banh trang, mam). Thay bien Ba Dong -> cho Tra Vinh thu 5-7 loai banh Khmer duoi mai che. Thay thuyen sang som -> hoc nau bun nuoc leo tai nha vuon (~100k/nguoi). Mua to: ngoi ca phe nhin song Tien, viet blog, chinh anh.',
    'mistakes': ['Dat khach san xa cho sang - bo lo bua sang ngon nhat (het truoc 09:30)', 'Di tour xe du lich -> khong vao duoc hang quan nho ven duong', 'Khong mang tien mat le -> nhieu quan cho khong co QR', 'An theo gio Sai Gon (12h-13h) -> quan mien Tay dong cua tu 11:30', 'Khong hoi "co gi dac biet hom nay?" -> bo qua mon theo mua', 'Mua keo dua o diem du lich thay vi xuong -> gia cao 40%, chat luong thap hon'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-tet-flower-special',
    'title': 'Tet Nguyen Dan - Hoa Cai Mon & Lang nghe',
    'profile': 'gia dinh dip Tet',
    'duration': '3 ngay',
    'provinces': ['Ben Tre', 'Vinh Long'],
    'season': 'thang 1-2',
    'summary': 'Lich trinh 3 ngay Tet Nguyen Dan tai Ben Tre + Vinh Long cho gia dinh, ngan sach 1,6-2,1 trieu/nguoi. Bao gom cho hoa Cai Mon, lang gom Mang Thit, cu lao An Binh, an uong dac san va tips thuc te dip Tet.',
    'content': 'Ngay 1 Ben Tre: Sang som di cho hoa Cai Mon (dep nhat 23-27 Tet), An bun Ben Tre, Vuon mai vang Cai Mon, Chieu ve xuong keo dua Thanh Long (tang qua Tet), Nhan phong khach san. Ngay 2 Vinh Long: Xe sang Vinh Long, Lang gom Mang Thit (lo gom va nuoc nguoc dep), Cu lao An Binh bang pha, Dap xe vuon vuon Tet, Toi an lau (do Tet nhieu noi nghi). Ngay 3: Cho noi Cai Be som (Tet gio Tet van hop), Ve HCM.',
    'budget': 'Luu tru 2 dem: 700-900k | An uong 9 bua: 400-500k | Di chuyen: 200-300k | Tham quan + mua sam: 300-400k',
    'total_cost': '1.600.000 - 2.100.000 VND/nguoi',
    'packing': ['Kem chong nang SPF50+', 'Ao dai hoac ao truyen thong chup anh', 'Giay/dep chong tham', 'Mu rong vanh hoac non la', 'Tui vai tai su dung dung do mua sam', 'Thuoc chong say xe', 'Tien mat toi thieu 1,5 trieu/nguoi', 'Binh nuoc 500ml', 'May anh hoac tripod mini', 'Thuoc di ung neu co tre nho (phan hoa nhieu)'],
    'rainy_plan': 'Ngay 2 mua: Bo cu lao, thay bang Bao tang Vinh Long, lo gom Mang Thit co mai che, va nha tho Cai Mon kien truc Gothic. Chieu uong tra sen tai vuon nha.',
    'mistakes': ['Den cho hoa Cai Mon qua sat Tet (ngay 28-29) - hoa tan, nguoi ban don hang', 'Khong dat xe truoc - ngay giap Tet xe thue khan hiem, gia tang gap doi', 'Mang qua nhieu tien the - nhieu quan chi nhan tien mat', 'Di vao gio trua gat (11h-14h) tai cac vuon trai cay thay vi sang som hoac chieu mat', 'Mua hoa cay qua lon kho mang ve - chon cay nho vua xe 7 cho'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-nuoc-noi-season',
    'title': 'Mua nuoc noi thang 9-10 - Dac san canh chua',
    'profile': 'food & nature lover',
    'duration': '2 ngay',
    'provinces': ['Vinh Long'],
    'season': 'thang 9-10',
    'summary': 'Lich trinh 2 ngay mua nuoc noi Vinh Long thang 9-10 cho food & nature lover, ngan sach 800k-1tr/nguoi. Bao gom cho noi, cu lao An Binh, lang gom Mang Thit, an canh chua ca linh bong dien dien dac san mua, trai nghiem nau an cung dan dia phuong.',
    'content': 'Ngay 1: 05:30 Cho noi Cai Be thuyen nho (180k), 08:00 Ve an sang banh mi thit nuong Ben Tre (20k), 09:30 Thue xe may (100k/ngay), 10:00 Cu Lao An Binh - len muc nuoc lu, chup anh dong nuoc, 12:30 An trua canh chua ca linh bong dien dien tai nha dan (100k), 14:30 Trai nghiem nau an canh chua tai bep dan, 17:00 Lang gom Mang Thit ngap nuoc, 19:00 Nhan phong homestay, an toi. Ngay 2: 06:00 Chup anh binh minh mat nuoc, 08:30 An bun rieu bong dien dien (25k), 10:00 Tham lang gom, 13:00 Xe ve HCM.',
    'budget': 'Xe khu hoi 180k | Luu tru 220k | Xuong thuyen 250k | Di chuyen 170k | An uong 500k | Trai nghiem & mua sam 200k',
    'total_cost': '800k-1.5 trieu/nguoi (tuy chi tieu dac san va nhom di)',
    'packing': ['Ao chong nang dai tay mong', 'Dep xo ngon chong tron hoac sandal di nuoc', 'Kem chong nang SPF50+', 'Thuoc chong say song', 'Tui zip nhieu co', 'Binh nuoc 1L', 'Ao mua mong gon (KHONG dung o tren xuong)', 'May anh hoac tui chong nuoc cho dien thoai', 'Tien mat (nhieu quan cho khong nhan chuyen khoan)'],
    'rainy_plan': 'Buoi sang van di xuong duoc (mua chieu nhieu hon). Thay hoat dong ngoai troi chieu bang: Bao tang tinh Vinh Long (mien phi), hoc nau canh chua tai bep nha dan, ca phe Moc Mien view song ngam mua.',
    'mistakes': ['Dat lich trinh day vao buoi chieu - mua nuoc noi hay mua to tu 14:00-16:00', 'Khong mac ca tien thue xuong - hoi nha nghi bao gia chuan truoc', 'Bo qua cho sang som vi muon ngu them - day la thoi diem dep nhat', 'Mang dep thuong ra dong nuoc - tron va nguy hiem', 'Khong hoi truoc mua ca linh con khong - cuoi thang 11 la het'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-ok-om-bok-festival',
    'title': 'Le hoi Ok Om Bok - Tra Vinh',
    'profile': 'du lich le hoi',
    'duration': '2 ngay',
    'provinces': ['Tra Vinh'],
    'season': 'thang 10-11 am lich',
    'summary': 'Lich trinh 2 ngay chi tiet le hoi Ok Om Bok tai Tra Vinh, ngan sach 500-900k/nguoi, bao gom lich theo gio cu the, dia diem, an uong, luu tru, chi phi tung muc, tips le hoi, lich trinh mua, loi pho bien va packing list.',
    'content': 'Ngay 1: 12:00 Xe tu HCM (130-150k), 15:00 Den Tra Vinh, an bun nuoc leo (30k), 16:00 Thue xe may (120k/2 ngay), 16:30 Chua Ang nghe kinh chieu, 18:00 Chua Tra Cuon xem chuan bi le, 19:30 Le cung trang tai Ao Ba Om (chinh) - DUNG DEN TRE, 21:30 Dua ghe ngo tren song Tra Vinh. Ngay 2: 06:00 Chua Ang le rang don, 08:00 An sang banh canh Ben Co (20k), 09:00 Bao tang Van hoa Khmer (20k), 11:00 Cho Tra Vinh, 12:30 Ve HCM (130-150k).',
    'budget': 'Xe khach 2 chieu 260-300k | Thue xe may 2 ngay 200-240k | Luu tru 1 dem chia doi 100-140k | An uong 2 ngay 270-350k | Ve/tham quan 20-40k | Mua sam 50-100k',
    'total_cost': '900k-1.170k/nguoi (chia doi phong va xe may de giu duoi 900k)',
    'packing': ['Ao mua mong hoac poncho (bat buoc thang 10-11)', 'Balo nho 15-20L nhe', 'Giay/dep de bang chong tron', 'Kem chong nang SPF50+', 'Thuoc chong muoi dang xit (Ao Ba Om nhieu muoi luc toi)', 'Tien mat chia nho (nhieu sap khong nhan chuyen khoan)', 'Sac du phong', 'Khan quang co mong (vao chua khi mac ao coc tay)'],
    'rainy_plan': 'Le cung Trang van dien ra trong nha van hoa hoac hien chua khi mua - mang ao mua mong. Thay the dua ghe ngo bang Bao tang Van hoa Dan toc Khmer Tra Vinh (ve 20k, duong Nguyen Thi Minh Khai).',
    'mistakes': ['Den tre buoi le cung (sau 19:30) - khong thay gi vi qua dong', 'Khong dat xe may truoc, phai di xe om gia cat co mua le', 'Mang valy to thay vi balo - duong chua va bo song nhieu cho dat nen', 'Bo qua nghi thuc cung tai chua lang nho - trai nghiem that hon san khau chinh', 'Khong dat phong truoc it nhat 3 tuan - Tra Vinh het phong rat nhanh mua le hoi'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-bird-watching-season',
    'title': 'Ngam chim Vam Ho - Ben Tre thang 11',
    'profile': 'birdwatcher / nha tu nhien hoc',
    'duration': '2 ngay',
    'provinces': ['Ben Tre'],
    'season': 'thang 11-3',
    'summary': 'Lich trinh 2 ngay ngam chim Vam Ho - Ben Tre thang 11 danh cho birdwatcher/nha tu nhien hoc. Ngan sach uoc tinh 900k-1.32tr/nguoi, bao gom di chuyen, luu tru, an uong va ve tham quan. Diem nhan: san chim Vam Ho 70ha, thue thuyen vao rung ngap man, buoi chieu vang 16:00-18:00 xem chim ve to.',
    'content': 'Ngay 1: 06:00 Xe tu HCM (80k), 08:00 Den Ben Tre, an bun mam (30k), 09:00 Thue xe may (120k/ngay), 10:00 Mo Cay lang nghe keo dua, 12:00 An trua (50k), 13:30 Di ve huyen Giong Trom Vam Ho (30km), 15:00 Nhan phong nha nghi (100-140k/dem), 16:00-18:00 THOI GIAN VANG - Chim ve to, do an ve to hon thuyen 3-4 lan, 19:00 An toi tom cang xanh nuong (70k). Ngay 2: 05:00 Ra diem quan sat, 05:30-07:30 Gio vang sang - co, trich, bich kiem noi dau. Thue thuyen vao sau rung (250k/thuyen 4 nguoi), 08:00 An sang bun moc (25k), 10:00 Trai ran cu (neu mua) hoac di them kenh rach. Ve HCM 14:00.',
    'budget': 'Xe khach 160k + xe may thue 240k + xang 100k + ve tham quan 170k + an uong 280k + luu tru 200k + thuyen 250k + pha 30k = ~1.32tr. Tiet kiem xuong 900k neu di nhom chia xe va bo trai ran.',
    'total_cost': '900.000d - 1.320.000d/nguoi',
    'packing': ['Ong nhom 8x42 hoac 10x42 (bat buoc)', 'May anh + ong kinh tele toi thieu 300mm', 'Ao mua nhe/poncho', 'Quan ao mau trung tinh: xanh la, nau, be', 'Giay loi bun hoac dep quai hau chac chan', 'Kem chong muoi DEET >20%', 'Nuoc uong 1.5L/nguoi/buoi', 'So ghi chep chim (field notebook)', 'App eBird va iNaturalist cai san tren dien thoai', 'Kem chong nang SPF50+', 'Tui zip chong nuoc cho thiet bi dien tu'],
    'rainy_plan': 'Ngay mua nhe: van quan sat tu lan san chim voi ao mua mong. Mua nang: Bao tang Ben Tre (mien phi), lang nghe keo dua Mo Cay. Chieu thuong tanh sau 17:00 - ra bo song Ben Tre xem co ve to.',
    'mistakes': ['Den san chim luc 9-10 gio sang - da tre, chim tan dan', 'Khong thue thuyen, chi dung ngoai - bo lo 80% trai nghiem', 'Mac quan ao mau sang trang/do lam chim giat minh', 'Khong mang kem chong muoi - rung ngap man nhieu muoi du', 'Khong hoi gio thuy trieu truoc - thuyen vao kenh phu thuoc nuoc', 'Bo qua buoi chieu 16:00-18:00 - gio vang dep nhat cho nhiep anh'],
    'quality_score': 7.7
  },
  {
    'id': 'itinerary-summer-beach-tv',
    'title': 'He thang 6-8 - Bien Ba Dong Tra Vinh',
    'profile': 'gia dinh he',
    'duration': '3 ngay',
    'provinces': ['Tra Vinh'],
    'season': 'thang 6-8',
    'summary': 'Lich trinh 3 ngay chi tiet cho gia dinh he tai Bien Ba Dong, Tra Vinh trong thang 6-8, ngan sach ~940.000-1.350.000d/nguoi. Bao gom gio giac cu the, goi y an uong/luu tru, tong chi phi, lich thay the mua, tips gia dinh va packing list.',
    'content': 'Ngay 1: 06:30 Xe tu HCM (130-150k), 09:00 Den TP.TV, an hu tieu/banh canh, 10:00 Thue xe may (100k/ngay), 10:30 Chua Ang (10k), 12:00 An trua (50k), 13:30 Ao Ba Om, 15:00 Bao tang Khmer (10k), 17:00 Nhan phong khach san Duyen Hai (200-300k). Ngay 2: 06:00 Xe may ra Ba Dong Beach (80km), 08:00 Den bien, tam + chup anh, 11:30 An hai san (100-150k), 14:00 Quay ve, 16:00 Nhan phong, nghi. Ngay 3: 07:00 Chua Hang, 09:00 Lang Ca Hom det chieu, 11:30 An bun nuoc leo (30k), 13:00 Mua qua ve, 14:30 Xe ve HCM.',
    'budget': '~940.000-1.350.000d/nguoi cho toan bo 3 ngay (xe khach, luu tru, an uong, vui choi, qua)',
    'total_cost': '3.760.000-5.400.000d cho gia dinh 4 nguoi (940.000-1.350.000d/nguoi)',
    'packing': ['Kem chong nang SPF 50+', 'Ao phao tre em', 'Dep de day chong nong', 'Thuoc say xe, thuoc ha sot, bang ca nhan', 'Do boi + quan ao dai vao chua', 'Binh nuoc ca nhan', 'Tui zip dung dien thoai khi tam bien', 'Tien mat toi thieu 500.000d/nguoi/ngay'],
    'rainy_plan': 'Tham quan Bao tang Van hoa Dan toc Khmer Tra Vinh (mien phi), chua Kompong Chrây, lang nghe chieu Ca Hom (Cau Ke), an nha hang trong trung tam Tra Vinh.',
    'mistakes': ['Khong dat phong truoc - thang 7-8 het phong rat nhanh, dac biet cuoi tuan', 'Cho tre tam bien gio trua - nguy hiem do song manh va nang gat', 'Khong mang tien mat du - khu Duyen Hai it ATM, quan nho khong nhan chuyen khoan', 'Mac do ho khi vao chua Khmer - bi nhac nho hoac khong duoc vao', 'Bo qua an sang dia phuong - bo lo banh canh Ben Co va hu tieu Tra Vinh dac sac'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-budget-500k-3day',
    'title': '3 ngay 3 tinh duoi 500k/ngay backpacker',
    'profile': 'sinh vien backpacker sieu tiet kiem',
    'duration': '3 ngay',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh 3 ngay Vinh Long - Ben Tre - Tra Vinh cho sinh vien backpacker sieu tiet kiem, chi tiet tung gio, an uong, di chuyen, luu tru, tong chi phi ~420-460k/ngay neu di nhom.',
    'content': 'Ngay 1 Vinh Long: 07:00 Xe buyt (60k), 10:30 Bo ke song Long Ho, 12:00 Com tam ven duong (25k), 13:30 Bao tang Vinh Long (mien phi), 15:00 Van Thanh Mieu, 17:00 Pha sang Cu Lao An Binh (10k), 18:30 Nhan phong dorm (80-100k), an com cu lao. Ngay 2 Ben Tre: 06:00 Cho noi Cai Be (thue thuyen chia nhom), 09:00 Xe ben Tre (60k), 11:00 Xuong keo dua (thu gia 70-100k), 13:00 An bun da (25k), 15:00 Mo Cay lang nghe, 18:00 Dorm Ben Tre (80-120k). Ngay 3 Tra Vinh: 07:00 Xe sang TV (60k), 09:00 Chua Ang, Ao Ba Om, 12:00 An banh canh Ben Co (20k), 14:00 Xe ve HCM (130k).',
    'budget': 'Di mot minh: ~563k/ngay. Di nhom 3-4 nguoi + xe buyt toan bo: ~420-460k/ngay. Tong 3 ngay: 1.260k-1.690k.',
    'total_cost': '1.260.000 - 1.690.000 VND cho toan chuyen (tuy cach di nhom hay solo)',
    'packing': ['Ao phao mong hoac ao chong nang (bat buoc tren song)', 'Dep to ong hoac sandal chong nuoc', 'Ao dai tay va quan dai cho chua Khmer', 'Kem chong nang SPF 50+', 'Thuoc chong say song', 'Power bank dung luong lon', 'Tui zip chong nuoc cho dien thoai va vi', 'Khan mat nhanh kho', 'Binh nuoc ca nhan tai su dung', 'Tien mat 600-700k/ngay rut san tu ATM TP.HCM'],
    'rainy_plan': 'Vinh Long: Bao tang tinh + cho co mai che. Ben Tre: co so keo dua trong nha, ca phe nha co. Tra Vinh: Bao tang Van hoa Khmer, cac chua co mai - bo bien Ba Dong.',
    'mistakes': ['Den cho noi sau 9h sang - da tan het', 'Mac quan dui/ao ho vai vao chua Khmer - bi tu choi', 'Khong mac ca gia xuong va xe om - tra gap doi', 'Khong dat ve xe ve HCM truoc - het cho chieu toi', 'Khong gui ba lo truoc khi di tham quan sang - mang nang met', 'Quen mang du tien mat - nhieu quan nho khong nhan QR/chuyen khoan'],
    'quality_score': 8.3
  },
  {
    'id': 'itinerary-motorbiketour-3day',
    'title': 'Tour xe may 3 ngay xuyen 3 tinh',
    'profile': 'motorbikers',
    'duration': '3 ngay',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'mua kho',
    'summary': 'Lich trinh xe may 3 ngay xuyen Vinh Long - Ben Tre - Tra Vinh voi gio giac cu the, quan an thuc te, luu tru, tong chi phi 600-850k/nguoi/ngay, tips cho biker va lich trinh mua du phong.',
    'content': 'Ngay 1 Vinh Long: 06:00 Khoi hanh (tranh nang gat), 08:30 Den Vinh Long - An bun rieu oc, 09:30 Cu Lao An Binh xe may loi theo duong nho, 12:00 An com gia dinh (50k), 14:00 Lang gach Mang Thit, 16:30 Nhan phong. Ngay 2 Ben Tre: 06:00 Sang som cross pha Vinh Long-Ben Tre (15k/xe may), 07:00 Cho noi, 09:30 Con Phung, 12:00 An trua, 14:00 Xuong keo dua Mo Cay, 17:00 Nhan phong. Ngay 3 Tra Vinh: 06:00 Xe may sang TV (100km), 08:30 Chua Ang, 10:00 Bao tang Khmer, 12:00 An banh canh, 14:30 Ba Dong beach (tuy thich, them 80km khu hoi), 17:30 Ve TV, xe ve HCM 19:00.',
    'budget': 'Xang 150-200k | An uong 450-600k | Luu tru 250-350k | Ve/pha 200-300k | Mua sam 100-200k',
    'total_cost': '1.150.000 - 1.650.000 VND/nguoi (600-850k/ngay khi di doi)',
    'packing': ['Ao chong nang dai tay + khau trang kin', 'Kinh mat chan gio', 'Giay kin chac', 'Kem chong nang SPF50+', 'Tui chong nuoc dung dien thoai + giay to', 'Bom mini + va xe + day buoc do', 'Tien mat 500k du phong', 'Binh nuoc 1L'],
    'rainy_plan': 'Uu tien diem trong nha: lang nghe banh trang/keo dua (mai che), bao tang Tra Vinh (mien phi), chua Khmer (mai rong). Bo Bien Ba Dong vi duong dat tron nguy hiem. Them thoi gian o cho dia phuong.',
    'mistakes': ['Xuat phat sau 08:00 - nang 09:00 rat gat, de kiet suc', 'Khong mang tien mat - quan nho khong nhan QR/the', 'Mac quan dui vao chua Khmer - bi tu choi', 'Khong book phong truoc dip cuoi tuan', 'Chay xe theo Google Maps khong offline - song yeu o cu lao'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-ocop-shopping-deep',
    'title': 'OCOP Deep Shopping Tour 2 ngay',
    'profile': 'nguoi mua dac san / nha phan phoi',
    'duration': '2 ngay',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh OCOP Deep Shopping Tour 2 ngay xuyen Vinh Long - Ben Tre - Tra Vinh, chi tiet theo gio, cho nguoi mua dac san va nha phan phoi, ngan sach 2-5 trieu/nguoi.',
    'content': 'Ngay 1 Vinh Long+Ben Tre: 07:00 Xe tu HCM (80k), 09:30 Vinh Long - Cho dac san OCOP tinh (tam duong Hung Vuong, mua ruou nep, banh phong, gao), 11:30 Xe sang Ben Tre, 13:00 Xuong keo dua Thanh Long (so sanh gia si/le, hoi them dat hang), 15:00 HTX Dua Ben Tre (10k san pham OCOP), 17:00 Nhan phong. Ngay 2 Tra Vinh: 07:00 Xe sang TV (80k), 08:30 Lang det chieu Ca Hom - mua buon (hoi chu nhan 0963...), 10:30 Bao tang Khmer mua qua lu nieem, 11:30 Cho Tra Vinh - thot not, banh Khmer, 13:30 Xe ve HCM.',
    'budget': 'An uong: 500k | Xe+pha: 350k | Luu tru: 350k | Mua sam: 900k-3.8tr -> Tong: ~2.1tr - 5tr/nguoi',
    'total_cost': '2.100.000 - 5.000.000 VND / nguoi',
    'packing': ['Thung xop 30L + 2 tui da gel', 'Tui vai lon tai su dung x3', 'Can mini dien tu', 'May anh / dien thoai dung luong lon (chup tem OCOP)', 'Danh sach san pham can tim in san', 'Tien mat ~2tr/nguoi + the du phong', 'Thuoc say xe', 'Dep sandal chong tron', 'Binh nuoc 1L + khau trang'],
    'rainy_plan': 'Thay Lang nghe Mo Cay bang Bao tang Ben Tre; dat hang HTX Trai cay qua hotline; doi Lang chieu Ca Hom sang sang som hom sau; tranh di pha khi gio cap 4 tro len.',
    'mistakes': ['Den muon sau 9h - mat hang ngon va co hoi gap chu co so', 'Khong hoi gia si vi ngai', 'Mua qua nhieu hang tuoi khong tinh duoc chi phi van chuyen', 'Khong xin hoa don VAT', 'Khong mang du tien mat', 'Dat phong TP.HCM va chay ve trong ngay - qua met, bo lo nhieu diem'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-history-war-trail',
    'title': 'Lich su khang chien - Dong Khoi & Di tich',
    'profile': 'du lich lich su / hoc sinh',
    'duration': '3 ngay',
    'provinces': ['Ben Tre', 'Vinh Long'],
    'season': 'bat ky',
    'summary': 'Lich trinh 3 ngay du lich lich su khang chien Ben Tre + Vinh Long cho hoc sinh, ngan sach ~1tr/nguoi. Ngay 1: Ben Tre - Dong Khoi Mo Cay, Khu luu niem Nguyen Thi Dinh. Ngay 2: Di tich Ben Tre + chuyen sang Vinh Long. Ngay 3: Di tich Nam Ky Khoi Nghia va ve. Chi phi uoc tinh ~1.39tr (co the rut ve 1tr bang tiet kiem).',
    'content': 'Ngay 1 Ben Tre: 08:00 Khu luu niem Nguyen Thi Dinh (30k ve, hoi truoc HDV), 10:00 Di tich Dong Khoi Mo Cay (10k, dong cua T2), 12:00 An bun nuoc leo (30k), 13:30 Bao tang Ben Tre (15k, phim tu lieu 30 phut), 16:00 Nhan phong. Ngay 2 Ben Tre+VL: 08:00 Tai lieu "Nghe am ban Dong Khoi" tai nha van hoa, 10:00 Xe sang Vinh Long (60k), 12:30 Nhan phong, an com gia dinh, 14:00 Bao tang tinh Vinh Long (tu lieu khang chien Minh Tay), 16:00 Nha cu lanh tu Nguyen Trung Truc (mien phi). Ngay 3: 08:00 Di tich Nam Ky Khoi Nghia (tinh Van), 11:00 Ve HCM.',
    'budget': 'Di chuyen: 400k | An uong: 390k | Luu tru: 375k | Ve & linh tinh: 225k | Tong: ~1.39tr (co the toi uu ve ~950k neu ghep doan lon va tu tuc bua sang)',
    'total_cost': '~1.39tr/nguoi (toi uu ve ~950k neu ghep doan lon)',
    'packing': ['Giay de bang chong tron', 'Kem chong nang SPF50+, non rong vanh', 'Ao mua gon loai poncho', 'Thuoc chong muoi', 'So tay + but ghi chep', 'Sac du phong', 'Tien mat toi thieu 500k/ngay/nguoi', 'Tui ziplock dung giay to khi di pha', 'Quan dai hoac vay qua goi'],
    'rainy_plan': 'Uu tien bao tang tinh Ben Tre va Vinh Long (co mai che toan bo). Bo dia dao Lang Tre (tron truot nguy hiem) va di chuyen xe may. Them xem phim tu lieu tai phong chieu bao tang (lien he truoc). Thue xe 16 cho ca doan ~500k/ngay thay vi xe may.',
    'mistakes': ['Khong dat truoc huong dan vien bao tang - den noi khong co nguoi dan giai', 'Mac quan short, ao ba lo vao khu tho tu - bi tu choi vao', 'Den di tich Dong Khoi Mo Cay vao thu 2 - dong cua bao duong', 'Khong mang tien mat - nhieu di tich va quan an khong nhan the/QR', 'Thue xe om khong thoa gia truoc - de bi chan chem voi khach doan', 'Bo qua bao tang, chi den di tich ngoai troi - mat boi canh lich su, kho hieu'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-craft-village-maker',
    'title': 'Lang nghe Maker Tour - Tu tay lam gom/det/keo',
    'profile': 'hands-on traveler / workshop lover',
    'duration': '3 ngay',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh 3 ngay Lang nghe Maker Tour tai Vinh Long - Ben Tre - Tra Vinh, ngan sach 1-2tr/nguoi, gom workshop gom Mang Thit, keo dua Mo Cay, det chieu Nhon Thanh, gom Khmer Chau Thanh.',
    'content': 'Ngay 1 Vinh Long: 08:00 Xe HCM->VL, 11:00 Nhan phong, an trua bun ca, 13:00 Lang gach-gom Mang Thit - xin tham gia vo dat gom (25k/nguoi/phien), 16:30 Xem lo gom nung qua dem, 18:30 An toi. Ngay 2 Ben Tre: 07:00 Xe sang BT, 09:00 Xuong keo dua Mo Cay - thu lam keo (70k/nguoi), 11:30 An trua (50k), 14:00 Lang de banh trang - thu nuong banh trang tren bep than (50k), 17:00 Nhan phong. Ngay 3 Tra Vinh: 07:30 Xe sang TV, 09:00 Lang det chieu Nhon Thanh Cau Ke (dat hang rieng hoac thu det 1 dam), 12:00 An banh canh, 14:00 Lo gom Khmer Chau Thanh (gom Khmer khac gom Viet), 17:00 Xe ve HCM.',
    'budget': 'Tong uoc tinh 2.030.000-2.730.000d/nguoi, gom di chuyen, workshop, an uong, luu tru, tham quan. Co the rut xuong duoi 2tr neu bo 1 workshop va di xe buyt thay xe may.',
    'total_cost': '2.030.000-2.730.000d/nguoi',
    'packing': ['Quan ao cu/toi mau du phong cho workshop (1-2 bo)', 'Dep sandal chiu nuoc + giay bata nhe', 'Ao mua tien loi (khong cong kenh)', 'Khan lau tay nho + wet wipe', 'Tui zip dung do tu lam (gom nho, keo)', 'Kem chong nang SPF50+', 'Binh nuoc 500ml tai su dung', 'Power bank (lang nghe khong co o cap cong cong)', 'Tien mat toi thieu 1,5 trieu/nguoi', 'So tay nho ghi ky thuat hoc duoc o workshop'],
    'rainy_plan': 'Ngay 1: Bao tang Vinh Long thay cho noi. Ngay 2: Workshop keo dua van duoc (co mai che), thay Con Phung bang Nha co Binh Thuy. Ngay 3: Goi truoc xac nhan lo gom Khmer, neu nghi thay bang Bao tang Van hoa Dan toc Khmer Tra Vinh. Luon mang ao mua tien loi.',
    'mistakes': ['Khong dat truoc workshop - lo/xuong co the ban don lon, khong tiep khach le', 'Mac do dep di workshop gom - dat set va pham mau khong tay duoc', 'Thue xe may khong kiem tra thang, xang truoc khi di', 'Toi lang nghe buoi trua (11:30-13:30) - tho nghi, khong ai tiep', 'Khong doi tien le - pha, do, mua qua vat can 5.000-20.000d, ATM o huyen hiem', 'An o quan du lich thay quan dia phuong - dat hon, kem vi, mat trai nghiem am thuc'],
    'quality_score': 8.2
  },
  {
    'id': 'itinerary-cycling-mekong',
    'title': 'Dap xe Mekong Delta 4 ngay',
    'profile': 'cyclist / active traveler',
    'duration': '4 ngay',
    'provinces': ['Vinh Long', 'Ben Tre'],
    'season': 'mua kho',
    'summary': 'Lich trinh dap xe 4 ngay Vinh Long + Ben Tre, ngan sach ~1.4-1.7tr/nguoi, chi tiet theo gio tung ngay, co phuong an mua, packing list va canh bao loi thuong gap cho cyclist.',
    'content': 'Ngay 1 Vinh Long: 06:00 Di xe (cu lao An Binh dat truoc): pha 10k, thue xe dap 60k/ngay, 07:00 Dap xe 15km vong cu lao: vuon trai cay, chua Tien Chau, bai bien dat, 11:00 Nghi an trua nha dan (50k), 14:00 Lang gach Mang Thit, 17:00 Ve homestay. Ngay 2: 06:30 Dap xe 20km: Vinh Long->Cai Be (qua ben pha), 09:00 Cho noi Cai Be tu thuyen nho, 12:00 Xe buyt sang Ben Tre (80k). Ngay 3 Ben Tre: 06:30 Cu Lao Minh dap xe 25km vong, 10:00 Mo Cay keo dua, 14:00 Bai bien Con Phung, 17:00 Homestay Giong Trom. Ngay 4: 06:30 Dap xe 15km bo song BT, 10:00 Thuyen Vam Ho, 14:00 Xe ve HCM.',
    'budget': 'Luu tru 3 dem: 630k-840k | An uong 4 ngay: 480k-600k | Do/pha/ve: 180k | Nuoc + phu phi: 100k',
    'total_cost': '1.390.000 - 1.720.000 VND/nguoi (co the toi uu ve ~1.3tr neu chon dorm va tu mua nuoc)',
    'packing': ['Mu bao hiem xe dap + kinh chong UV', 'Ao cycling dai tay chong nang UPF 50+', 'Quan cycling co pad (bat buoc cho 4 ngay dap)', 'Dep xang-dan nhe de di bo tham quan', 'Binh nuoc 750ml + vien dien giai', 'Bo va xe mini + bom tay co nho', 'Kem chong nang SPF50+', 'Tui ghi dong chong nuoc (handlebar bag)', 'Maps.me tai offline vung Vinh Long + Ben Tre', 'Goi cuu thuong nho: bang ca nhan, thuoc dau bung, thuoc dau dau'],
    'rainy_plan': 'Ngay 1 mua: Bao Tang Vinh Long + Lang gom Mang Thit (trong nha xuong). Ngay 2-3 mua: Thue xe om di chuyen giua diem, them ~100k/ngay. Mua rao chieu mua kho thuong chi 30 phut, ngoi quan ca phe cho qua.',
    'mistakes': ['Xuat phat sau 07:00 - nang 09:00 rat gat, de kiet suc', 'Khong mang do va xe - duong hem thuong co dinh, tiem sua xe cach xa', 'Mac ao thun thuong - ra mo hoi nhieu, de cam. Dung ao cycling UPF dai tay', 'Tin 100% vao Google Maps - nhieu con duong mon ven song chua cap nhat, nen hoi nguoi dia phuong', 'An hai san ven duong gia re khong ro nguon: nguy co ngo doc cao, chon quan dong khach dia phuong'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-vegan-tour',
    'title': 'Hanh trinh am thuc chay mien Tay 3 ngay',
    'profile': 'vegan / chay truong',
    'duration': '3 ngay',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'bat ky',
    'summary': 'Lich trinh am thuc chay mien Tay 3 ngay cho vegan/chay truong, di chuyen qua Vinh Long, Ben Tre, Tra Vinh. Bao gom gio cu the, ten quan, gia tung muc, tips chay truong, lich trinh mua va packing list. Tong chi phi uoc tinh 825-1.210k/nguoi.',
    'content': 'Ngay 1 Vinh Long: 07:00 Xe tu HCM, 10:00 An sang chay tai Chua Thanh Son (chua co bep chay, 30k), 11:00 Bao tang Vinh Long, 13:00 An trua com chay giao doi (35k), 15:00 Cu Lao An Binh - vuon trai cay an tai vuon, 18:30 An toi chay quan Ba Noi. Ngay 2 Ben Tre: 07:00 Xe BT, 09:00 Thu tay lam keo dua chay (70k), 12:00 An trua chay nha hang Thanh Hoa (40k), 14:00 Vuon cay Cai Mon thu trai cay, 18:00 Nhan phong, bua toi thieu an chay tien roi. Ngay 3 Tra Vinh: 08:00 Xe sang TV, 09:00 Chua Ang (xin com chay chua, 20k tu nguyen), 11:30 An banh canh chay tai cho, 14:00 Xe ve HCM.',
    'budget': 'Di chuyen 290-380k + An uong 270-400k + Luu tru 155-210k + Tham quan 60-120k + Qua 50-100k = Tong 825-1.210k/nguoi',
    'total_cost': '825.000-1.210.000 VND/nguoi',
    'packing': ['Kem chong nang SPF 50+', 'Non rong vanh / mu coi', 'Ao dai tay chong nang', 'Dep quai chac chan', 'Ao mua tien loi (gon)', 'Binh nuoc giu nhiet', 'Tien mat 500-800k', 'Thuoc dau bung / dau dau', 'Xit muoi', 'Power bank', 'Tui zip dung dien thoai (di do)', 'Giay to tuy than photo', 'Khan mat nhanh kho', 'Quan dai (vao chua)', 'Snack chay du phong'],
    'rainy_plan': 'Ngay 1 mua: Bo cu lao, thay bang Bao tang tinh Vinh Long va xuong gom Dinh Quoi co mai che. Ngay 2 mua: Bo cheo thuyen, ghe Trung tam van hoa dua Ben Tre trong nha. Ngay 3 mua: Bo bien Ba Dong, tham quan he thong chua Khmer noi thanh Tra Vinh.',
    'mistakes': ['Khong noi ro "chay truong khong hanh toi" - nhan chay ngu vi tan van co hanh phi', 'Dat tour tron goi khong kiem tra menu - bua an co hai san', 'Di cu lao buoi trua khong mang o/non - chay nang trong 30 phut', 'Khong dat phong truoc cuoi tuan/le - het phong hoac gia tang gap doi', 'Tin Google Maps quan an vung tinh - nhieu quan da dong hoac doi menu', 'Mang qua nhieu hanh ly khi di do - bat tien, ton tien gui', 'Khong mang tien mat - ATM vung tinh it, quan nho khong nhan chuyen khoan'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-digital-nomad',
    'title': 'Digital Nomad 1 tuan Vinh Long - Lam viec & kham pha',
    'profile': 'remote worker / digital nomad',
    'duration': '7 ngay',
    'provinces': ['Vinh Long'],
    'season': 'bat ky',
    'summary': 'Lich trinh 7 ngay chi tiet cho digital nomad tai Vinh Long voi ngan sach 800k-1.5tr/ngay. Tong chi phi uoc tinh ~6.24 trieu, bao gom lich theo gio cu the, goi y quan an/ca phe voi gia thuc te, tips WiFi/workspace, lich trinh mua, loi pho bien va packing list day du.',
    'content': 'Ngay 1 (Den+Setup): Nhan phong khach san co WiFi tot (385k/dem), kiem tra toc do mang thuc (>20Mbps), an toi bo ke song. Ngay 2-5 (Work+Explore): 07:00-09:00 An sang bun rieu + di bo sang; 09:30-12:00 Lam viec tai ca phe Co Gai (WiFi oi nhat, may lanh); 12:00-14:00 An trua, nghi; 14:00-17:00 Lam viec tiep hoac tham quan 1 diem; 17:00-19:00 Tham cu lao/lang nghe; 19:00 An toi + lang giai. Cuoi tuan: Cho noi Cai Be, Cu Lao An Binh, Van Thanh Mieu. Ngay 7 (Ra di): Ve HCM hoac den tinh moi.',
    'budget': '800k-1.5tr/ngay | Tong 7 ngay ~6.240.000d (trung binh 892k/ngay)',
    'total_cost': '~6.240.000d cho 7 ngay (luu tru 2.700k + an uong 1.400k + di chuyen 660k + tham quan 150k + mua sam 500k + du phong 480k + ca phe 350k)',
    'packing': ['Laptop + sac', 'Power bank 20.000mAh', 'Tai nghe chong on', 'Hub USB-C', 'SIM 4G Viettel backup', 'Quan short + ao thun 5 bo', 'Ao mua gap gon', 'Mu rong vanh', 'Kem chong nang SPF50+', 'Xit chong muoi', 'Thuoc chong say tau/thuyen', 'Thuoc tieu chay', 'Binh nuoc 750ml tai su dung', 'Tui chong nuoc A4 cho laptop', 'Tien mat ~2 trieu + the ATM noi dia'],
    'rainy_plan': 'Mua nhanh tanh - o lai lam viec full day hoac tham Bao tang Vinh Long (20k), Van Thanh Mieu co mai che, Coopmart food court. Hoan cho noi sang ngay khac. Mua ao mua cho ~50k neu van muon di cu lao.',
    'mistakes': ['Dat phong xa trung tam vi re hon - mat tien di chuyen gap doi khoan tiet kiem', 'Khong kiem tra toc do WiFi thuc te truoc khi check-in', 'An tai nha hang "du lich" gan ben pha - gia gap doi chat luong kem', 'Di cho noi Cai Be luc 09:00 - cho hop tu 04:00-07:00 da tan', 'Khong mac ca khi thue xe may - gia niem yet 200k co the tra 150k', 'Mang laptop di thuyen khong co tui chong nuoc', 'Khong dat lich lam viec ro rang truoc khi di kham pha'],
    'quality_score': 7.3
  },
  {
    'id': 'itinerary-international-tourist',
    'title': '3 ngay Mekong Delta cho khach quoc te',
    'profile': 'international tourist (English)',
    'duration': '3 ngay',
    'provinces': ['Vinh Long', 'Ben Tre', 'Tra Vinh'],
    'season': 'thang 11-4',
    'summary': '3-day detailed Mekong Delta itinerary covering Vinh Long, Ben Tre, and Tra Vinh for international tourists. Budget USD 40-65/day. Includes hourly schedule, specific restaurant and accommodation recommendations, transport costs, rainy day alternatives, common mistakes, and packing list.',
    'content': 'Day 1 Vinh Long: 07:00 Bus from HCMC (60k), 10:00 Arrive, check-in, 11:00 Ferry to Cu Lao An Binh (10k), 12:00 Local lunch at nha vuon (50k), 14:00 Cycling through orchards (60k/bike), 17:00 Van Thanh Mieu, 18:30 Riverside dinner. Day 2 Ben Tre: 07:00 Bus (60k), 09:00 Cai Lon floating market by private boat, 11:00 Con Phung - kayaking (150k), 13:30 Lunch + coconut candy factory tour (70k), 16:30 Check-in. Day 3 Tra Vinh: 07:30 Bus (80k), 09:30 Ang Pagoda (10k), 11:00 Ba Om Pond, 13:00 Lunch banh canh Ben Co (25k), 14:30 Khmer Culture Museum (10k), 16:30 Hang Pagoda, 18:00 Bus back HCMC (130k).',
    'budget': 'Accommodation: $35-50 | Transport: $30-45 | Meals: $25-40 | Activities: $20-30 | Extras: $10-15',
    'total_cost': 'USD 120-180 total (USD 40-60/day average)',
    'packing': ['Lightweight long pants (temples + mosquitoes)', 'Sandals with grip (wet dock planks)', 'Plastic dry bag for phone and passport', 'Insect repellent DEET 30%+', 'Small VND bills (50k, 100k notes)', 'Reusable water bottle', 'Portable power bank', 'Light rain poncho', 'Sunscreen SPF50+', 'Vietnamese phrasebook screenshots'],
    'rainy_plan': 'Swap canals for indoor coconut candy factories (Ben Tre), visit Vinh Long Market (covered), tour Khmer temples with poncho, substitute Ba Dong Beach with Vinh Long Museum ($0.50 entry).',
    'mistakes': ['Booking a rushed HCMC day tour covering all 3 provinces - you see nothing real', 'Arriving at Cu Lao An Binh past 11am when tour groups flood in', 'Accepting first boat charter price near tourist piers', 'Eating at English-menu restaurants near piers - walk one block inland', 'Forgetting sunscreen - river glare burns fast even on cloudy days'],
    'quality_score': 8
  },
  {
    'id': 'itinerary-group-company-retreat',
    'title': 'Team Building Retreat Cong ty 2 ngay',
    'profile': 'nhom cong ty 15-30 nguoi',
    'duration': '2 ngay',
    'provinces': ['Vinh Long', 'Ben Tre'],
    'season': 'bat ky',
    'summary': 'Lich trinh Team Building Retreat 2 ngay Vinh Long + Ben Tre cho nhom 15-30 nguoi, ngan sach 1,5-2,1 trieu/nguoi. Ngay 1: Cu Lao An Binh - Mang Thit - Mekong Riverside Resort. Ngay 2: Keo dua Thanh Long - Cai Mon - ve TP.HCM.',
    'content': 'Ngay 1: 07:00 Xe 45 cho khoi hanh HCM (thue 2 xe 45 cho, ~3tr/xe), 10:00 Den Vinh Long, pha sang Cu Lao An Binh (thue tau lon 500k), 11:00 Tro choi team building cuoc tren cu lao (thue xe dap theo nhom 20k/nguoi/gio), 12:30 An trua BBQ nha vuon (80k/nguoi), 15:00 Tham lang gach Mang Thit, 17:00 Check-in Mekong Riverside Resort, 19:00 An toi tiec tap the. Ngay 2: 08:00 An sang resort, 09:30 Xe sang Ben Tre, 10:30 Xuong keo dua Thanh Long - thu lam + mua qua (70k/nguoi), 12:30 An trua hai san (100k/nguoi), 14:00 Vuon cay Cai Mon, 16:00 Ve HCM.',
    'budget': '1.430.000 - 2.130.000d/nguoi (nhom 20 nguoi), bao gom xe, an uong 4 bua, luu tru 1 dem, ve vao cua va hoat dong',
    'total_cost': '1.430.000 - 2.130.000d/nguoi',
    'packing': ['Ao nhe thoang toi mau (tranh vet bun vuon)', 'Giay de bang hoac sandal co quai hau', 'Kem chong nang SPF50+ va mu rong vanh', 'Thuoc chong say xe', 'Tui zip chong nuoc cho dien thoai', 'Tien mat (nhieu noi chua nhan QR)', 'Tui vai nho dung do mua', 'Sac du phong'],
    'rainy_plan': 'Ngay 1: Thay cheo xuong bang nha co Binh Thuy, doi picnic sang an trong nha hang, van di Mang Thit vi co mai. Ngay 2: Thay dap xe bang Bao tang Ben Tre + xuong keo dua trong nha. Mua chieu thuong chi 30-60 phut, len lich buoi sang la on.',
    'mistakes': ['Den ben pha gio cao diem 7h-8h30 ma khong dat truoc - ket cung', 'Dat combo tour tron goi gia re ma khong kiem tra tung dich vu - hay bi cat bua hoac doi diem', 'Mua keo dua ngoai cho thay vi tai xuong - dat hon, it lua chon', 'Khong uong nuoc du - troi mien Tay nong am, de met hon TP.HCM', 'Quen xin hoa don khi thanh toan nhom - kho doi soat chi phi sau'],
    'quality_score': 8
  }
]

new_entities = []
skipped = []
for item in new_itineraries_raw:
    entity_id = item['id']
    if entity_id in existing_ids:
        skipped.append(entity_id)
        continue

    provinces_str = ', '.join(item['provinces'])
    packing_str = ', '.join(item['packing'])
    mistakes_str = '; '.join(item['mistakes'])

    entity = {
        'id': entity_id,
        'type': 'itinerary',
        'name': item['title'],
        'placeId': None,
        'summary': item['summary'],
        'source': 'curated',
        'status': 'verified',
        'verified': True,
        'confidence': 1.0,
        'updatedAt': '2026-06-11T00:00:00Z',
        'coords': None,
        'attributes': {
            'content': item['content'],
            'profile': item['profile'],
            'duration': item['duration'],
            'provinces': provinces_str,
            'season': item['season'],
            'budget': item['budget'],
            'total_cost_estimate': item['total_cost'],
            'packing_list': packing_str,
            'rainy_day_plan': item['rainy_plan'],
            'common_mistakes': mistakes_str,
            'quality_score': item['quality_score'],
            'traveler_type': item['profile']
        }
    }
    new_entities.append(entity)
    existing_ids.add(entity_id)

# Append
data['entities'].extend(new_entities)
after_count = len(data['entities'])

# Write
with open('C:/Code/vinhlong360/web/data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, separators=(',', ':'))

print(f'BEFORE: {before_count}')
print(f'ADDED: {len(new_entities)}')
print(f'SKIPPED (duplicates): {len(skipped)}')
print(f'AFTER: {after_count}')
if skipped:
    print(f'Skipped IDs: {skipped}')
