import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { DatabaseSync } from 'node:sqlite'
import path from 'node:path'
import fs from 'node:fs'
import { generateCategoryPlaceholder } from '../web-nuxt/composables/useCategoryPlaceholder'

const repoRoot = fs.existsSync(path.resolve('agent/data/vinhlong360.db'))
  ? path.resolve('.')
  : path.resolve('..')
const dbPath = path.join(repoRoot, 'agent/data/vinhlong360.db')
const dataJsonPath = path.join(repoRoot, 'web/data.json')
const publicImgDir = path.join(repoRoot, 'web-nuxt/public/img/entities')

let db: DatabaseSync

beforeAll(() => {
  expect(fs.existsSync(dbPath), `Database file must exist at ${dbPath}`).toBe(true)
  db = new DatabaseSync(dbPath, { readOnly: true })
})

afterAll(() => {
  if (db) {
    db.close()
  }
})

describe('Image Governance & Visual Asset Suite (100% Full Coverage)', () => {
  it('verifies 100% of entities in SQLite have valid images array and 0 broken local references', () => {
    const allEntities = db.prepare(`SELECT id, images FROM entities`).all() as { id: string; images: string }[]
    
    expect(allEntities.length).toBe(1772)

    for (const row of allEntities) {
      expect(row.images, `Entity ${row.id} must have non-empty images`).toBeDefined()
      expect(row.images).not.toBe('')
      expect(row.images).not.toBe('[]')

      let imageList: string[] = []
      try {
        imageList = JSON.parse(row.images)
      } catch (err) {
        throw new Error(`Entity ${row.id} has invalid JSON in images: ${row.images}`)
      }

      expect(imageList.length, `Entity ${row.id} must have at least 1 image`).toBeGreaterThan(0)

      for (const img of imageList) {
        // Must not contain mock/dummy URLs
        expect(img).not.toContain('example.test')
        expect(img).not.toContain('localhost')

        if (img.startsWith('/img/entities/')) {
          const filename = path.basename(img)
          const physicalPath = path.join(publicImgDir, filename)
          expect(fs.existsSync(physicalPath), `Local image ${img} referenced by entity ${row.id} must exist at ${physicalPath}`).toBe(true)
          
          const stat = fs.statSync(physicalPath)
          expect(stat.size, `Image ${filename} should be > 500 bytes`).toBeGreaterThan(500)
        }
      }
    }
  })

  it('verifies 100% of entities in web/data.json have valid images array matching SQLite', () => {
    expect(fs.existsSync(dataJsonPath)).toBe(true)
    const raw = fs.readFileSync(dataJsonPath, 'utf-8')
    const data = JSON.parse(raw)
    const entities = data.entities || []

    expect(entities.length).toBe(1772)

    const dummyEntities = entities.filter((e: any) => {
      const imgs = Array.isArray(e.images) ? e.images : []
      return imgs.some((img: string) => img.includes('example.test') || img.includes('localhost'))
    })
    expect(dummyEntities.length).toBe(0)

    const missingImages = entities.filter((e: any) => !Array.isArray(e.images) || e.images.length === 0)
    expect(missingImages.length).toBe(0)
  })

  it('verifies iconic enriched heritage entities have authentic provenance metadata in SQLite', () => {
    const enrichedIconicIds = [
      'khu-di-tich-ao-ba-om',
      'cau-my-thuan',
      'van-thanh-mieu',
      'chua-hang-kompong-chray',
      'con-phung-con-ong-dao-dua',
      'den-tho-bac-ho-tra-vinh',
      'chua-ong-met-botum-vong-sa-som-rong',
      'lo-gach-mang-thit',
      'nha-tho-cai-mon',
      'sau-rieng-cai-mon',
      'chua-nodol-tra-vinh',
    ]

    for (const id of enrichedIconicIds) {
      const row = db.prepare(`SELECT id, images, attributes FROM entities WHERE id = ?`).get(id) as { id: string; images: string; attributes: string }
      expect(row, `Entity ${id} must exist in DB`).toBeDefined()

      const images = JSON.parse(row.images)
      expect(images.length, `Entity ${id} must have at least 1 image`).toBeGreaterThan(0)
      expect(images[0]).toBe(`/img/entities/${id}.webp`)

      const attrs = JSON.parse(row.attributes || '{}')
      expect(attrs.image_author, `Entity ${id} must have author`).toBeDefined()
      expect(attrs.image_author.length).toBeGreaterThan(1)
      expect(attrs.image_license, `Entity ${id} must have license`).toBeDefined()
      expect(attrs.image_license).toMatch(/CC|Public Domain|Creative Commons|Tư liệu|Báo|Cổng TTĐT/i)
      const hasSource = Boolean(attrs.image_source || attrs.image_source_url)
      expect(hasSource, `Entity ${id} must have image_source or image_source_url`).toBe(true)

      const assetPath = path.join(publicImgDir, `${id}.webp`)
      expect(fs.existsSync(assetPath)).toBe(true)
      const stat = fs.statSync(assetPath)
      expect(stat.size).toBeGreaterThan(1024) // > 1KB
    }
  })

  it('verifies documentary journalistic photos have local WebP and authentic author/source attribution', () => {
    const documentaryIds = [
      // 16 Pilot Cultural / Terroir Entities
      'van-thanh-mieu',
      'dinh-long-ho',
      'chua-tien-chau-tien-chau-tu',
      'lo-gach-mang-thit',
      'khu-luu-niem-thu-tuong-vo-van-kiet',
      'khu-luu-niem-tran-dai-nghia-vinh-long',
      'chua-phat-ngoc-xa-loi',
      'khu-di-tich-ao-ba-om',
      'chua-ang-angkorajaborey',
      'den-tho-bac-ho-tra-vinh',
      'chua-hang-kompong-chray',
      'lang-nghe-banh-trang-my-long',
      'lang-nghe-banh-phong-son-doc',
      'con-phung-con-ong-dao-dua',
      'nha-tho-cai-mon',
      'lang-nghe-det-chieu-ca-hon',
      // 25 Culinary Heritage & Craft Entities (Batch 2)
      'banh-canh-ben-co',
      'banh-canh-bot-xat-ben-tre',
      'banh-tet-tra-cuon-co-huong',
      'bun-suong-tra-vinh',
      'chao-am-tra-vinh',
      'ca-chay-tra-on-rim-kho',
      'chuoi-dap-nuoc-cot-dua',
      'banh-xeo-oc-gao-con-phu-da',
      'hu-tieu-pate-ben-tre',
      'tau-hu-ky-my-hoa-chien-gion',
      'bun-nuoc-leo-tra-vinh',
      'bun-mam-vinh-long',
      'banh-dua-giong-luong',
      'banh-ray-khmer-la-dua',
      'khoai-lang-mam-song-cuon-la-cach',
      'com-hap-trai-dua',
      'che-chuoi-nuong',
      'ca-chay-song-hau',
      'lang-keo-dua-mo-cay',
      'lang-nghe-banh-tet-tra-cuon',
      'lang-hoa-kieng-cai-mon-cho-lach',
      'lang-det-chieu-cu-lao-dai',
      'banh-trang-cu-lao-may-lang-nghe-banh-trang',
      'lang-det-chieu-ca-hom-ham-tan',
      'hop-tac-xa-buoi-nam-roi-my-hoa',
      // 30 Heritage Communal Houses, Ancient Pagodas & Memorials (Batch 3)
      'dinh-long-thanh-long-thanh-vo-mieu',
      'chua-ong-that-phu-mieu',
      'chua-ba-thien-hau-vinh-long',
      'chua-shanghamangala-khmer-vung-liem',
      'dinh-tan-hoa',
      'dinh-tan-giai-vinh-long',
      'khu-luu-niem-thu-tuong-chinh-phu-vo-van-kiet',
      'chua-giac-thien-vinh-long',
      'dinh-cai-von',
      'chua-khmer-phu-ly',
      'chua-ang',
      'ao-ba-om-ao-vuong',
      'chua-hang-wat-kompong-chray',
      'chua-kompong-ong-met',
      'chua-co-chua-nodol-chua-phno-don',
      'chua-vam-ray',
      'phuoc-minh-cung-chua-ong-tra-vinh',
      'chua-giac-linh-tra-vinh',
      'dinh-long-duc-tra-vinh',
      'chua-o-mich-hung-hoa',
      'dinh-phu-le-ben-tre',
      'dinh-binh-hoa-ben-tre',
      'dinh-tan-thach',
      'dinh-dai-dien',
      'dinh-ran-dinh-thuy',
      'chua-van-phuoc-binh-dai',
      'chua-tuyen-linh-ben-tre',
      'chua-hoi-ton-co-tu',
      'khu-luu-niem-nguyen-dinh-chieu',
      'khu-luu-niem-nu-tuong-nguyen-thi-dinh',
      // 36 Homestays, Farmstays & Eco-Resorts across Tam Vùng (Batch 4)
      'homestay-ut-trinh',
      'phuong-thao-homestay',
      'nam-thanh-homestay',
      'ut-thuy-homestay',
      'ngoc-phuong-homestay',
      'vinh-sang-resort',
      'mekong-pottery-homestay',
      'somo-farm-cuu-long',
      'riverside-park-eco-resort',
      'homestay-bay-thoi',
      'homestay-cu-lao-may',
      'diem-du-lich-nha-dua-cocohome',
      'forever-green-resort',
      'homestay-nam-ham-luong',
      'homestay-dua-ben-tre',
      'homestay-lang-be',
      'homestay-nguoi-giu-rung',
      'mango-home-ben-tre',
      'mekong-home',
      'maison-du-pays-de-ben-tre',
      'nhon-thanh-homestay',
      'rooster-mekong-resort',
      'farmstay-sinh-thai-nguyen-gia',
      'khach-san-ham-luong',
      'con-chim-homestay',
      'homestay-bep-nam-bo-xua-con-chim',
      'homestay-tu-pha-con-chim',
      'suonsia-homestay',
      'mekong-garden-homestay',
      'homestay-sokfram',
      'homestay-khmer-tra-vinh',
      'khu-du-lich-bien-ba-dong',
      'duyen-hai-homestay',
      'le-ngan-homestay',
      'nha-nghi-nha-co-dai-an',
      'khach-san-hai-duong-i',
      // 36 OCOP 3-5 Star Products & Terroir Specialties (Batch 5)
      'buoi-nam-roi-binh-minh',
      'cam-sanh-tam-binh',
      'khoai-lang-binh-tan',
      'sau-rieng-ri6',
      'gom-do-mang-thit',
      'banh-trang-nem-cu-lao-may',
      'nhan-xuong-com-vang',
      'chom-chom-binh-hoa-phuoc-rambutan',
      'xoai-cat-num-vung-liem',
      'chao-dua-thuan-duyen-tam-binh',
      'cuu-long-my-tuu-ruou-ocop-mang-thit',
      'sau-rieng-say-thang-hoa-sau-ri',
      'buoi-da-xanh-ben-tre',
      'keo-dua-ben-tre',
      'ruou-phu-le-ba-tri',
      'dua-xiem-xanh',
      'ngheu-thanh-hai',
      'cua-bien-thanh-phu',
      'sau-rieng-cai-mon',
      'chom-chom-cho-lach',
      'mut-dua-non',
      'tinh-dau-dua',
      'tranh-dua-cocohand',
      'ruou-dua-ben-tre',
      'dua-sap-cau-ke',
      'mat-hoa-dua-va-duong-hoa-dua-tra-vinh-ocop-5-sao',
      'vicosap-keo-dua-sap-ocop-5-sao',
      'cha-hoa-nam-thuy',
      'tom-kho-vinh-kim',
      'nuoc-mam-ruoi-long-vinh',
      'banh-tet-tra-cuon',
      'chuoi-ta-qua',
      'chu-u-ba-dong',
      'ruou-quach-cau-ngang',
      'mam-bo-hoc-tra-vinh',
      'tom-kho-cham-mam-chua-ngot-duyen-hai',
      // 36 Cultural Luminaries, Historical Figures & Master Artisans (Batch 6)
      'thoai-ngoc-hau',
      'phan-thanh-gian',
      'vo-van-kiet',
      'tran-dai-nghia',
      'tran-dai-nghia-pham-quang-le',
      'pham-hung',
      'pham-hung-pham-van-thien',
      'nguyen-thong',
      'tong-huu-dinh',
      'tran-quang-quon',
      'nghe-nhan-chau-xuong',
      'nghe-nhan-nguyen-thi-thoi',
      'ut-tra-on',
      'le-thuy',
      'tong-phuoc-hiep',
      'chau-van-sanh-cong-tu-loi',
      'nguyen-dinh-chieu',
      'nguyen-thi-dinh',
      'suong-nguyet-anh',
      'nguyen-ngoc-thang',
      'dong-van-cong',
      'huynh-ngoc-khiem-huong-liem',
      'truong-duy-toan',
      'thanh-ton',
      'ba-du',
      'thanh-huong',
      'nguyen-van-ton-thach-duong',
      'tuong-quan-nguyen-van-ton',
      'vien-chau-huynh-tri-ba',
      'nguyen-thi-ut',
      'nguyen-thien-thanh',
      'thach-boi',
      'thach-oai',
      'thach-sok-xane',
      'thanh-loan',
      'truong-xuan',
      // 25 Festival & Cultural Event Entities (Batch 7)
      'le-hoi-ok-om-bok',
      'le-hoi-chol-chnam-thmay-tai-chua-ky-son',
      'le-hoi-chol-chnam-thmay-va-sen-dolta',
      'sen-dolta',
      'le-hoi-dom-long-neak-ta',
      'hoi-thi-ghe-ngo-mo-rong-tinh-tra-vinh-dua-ghe-ngo-truyen-thong-tra-vinh',
      'tuan-le-van-hoa-du-lich-gan-voi-le-hoi-ok-om-bok',
      'le-hoi-nghinh-ong-duyen-hai',
      'le-hoi-nghinh-ong-binh-thang',
      'le-hoi-cung-bien-my-long',
      'le-cung-bien-dong-cao',
      'le-hoi-nghinh-ong-lang-con-tau',
      'le-hoi-ky-yen-dinh-phu-le',
      'le-hoi-ky-yen',
      'le-hoi-ky-yen-ha-dien-dinh-tan-giai',
      'lang-ong-tien-quan-thong-che-dieu-bat-tuong-quan-nguyen-van-',
      'le-hoi-van-thanh-mieu',
      'le-via-quoc-cong-tong-phuoc-hiep',
      'le-gio-phan-thanh-gian-tai-van-thanh-mieu',
      'le-gio-nguyen-dinh-chieu',
      'festival-dua-ben-tre',
      'festival-dua-sap-cau-ke-tra-vinh',
      'festival-gach-gom-do-kinh-te-xanh-tinh-vinh-long-vinh-long',
      'ngay-hoi-van-hoa-the-thao-va-du-lich-huyen-cho-lach-ben-tre',
      'ngay-hoi-banh-dan-gian-nam-bo-ket-hop-hoi-cho-ocop-vinh-long-vinh-long',
      // 25 Islands, Revolutionary Relics & Museums across Tam Vùng (Batch 8)
      'can-cu-cach-mang-cai-ngang-vinh-long',
      'di-tich-can-cu-khu-uy-sai-gon-gia-dinh',
      'di-tich-duong-ho-chi-minh-tren-bien-thanh-phu',
      'khu-di-tich-can-cu-tinh-uy-tra-vinh',
      'cau-my-thuan',
      'bao-tang-vinh-long',
      'bao-tang-ben-tre',
      'bao-tang-van-hoa-dan-toc-khmer-tra-vinh',
      'mo-va-khu-luu-niem-nha-giao-vo-truong-toan',
      'cho-noi-tra-on-dc',
      'cho-noi-dua-song-thom-mo-cay',
      'nha-tho-chinh-toa-vinh-long',
      'nha-tho-cai-mon-cho-lach',
      'cu-lao-dai-cu-lao-thanh-binh-quoi-thien',
      'cu-lao-my-hoa',
      'con-chim',
      'con-tan-qui',
      'con-oc-hung-phong',
      'con-quy-song-tien-chau-thanh-ben-tre',
      'con-tam-hiep-dao-tam-hiep',
      'bai-bien-con-bung-thanh-hai',
      'bai-bien-mo-o-truong-long-hoa-tra-vinh',
      'rung-duoc-long-khanh',
      'rung-ngap-man-phong-ho-binh-dai-ben-tre',
      'canh-dong-muoi-bao-thanh',
      // 35 Cultural Attractions, Ancient Pagodas & Historical Relics (Batch 9)
      'can-cu-khu-uy-sai-gon-gia-dinh-tai-tan-phu-tay',
      'can-cu-tinh-uy-ben-tre-rung-la-thanh-phu',
      'cang-thi-ba-vat-di-chi-khao-co',
      'bung-lac-dia',
      'ben-tiep-nhan-vu-khi-con-tau',
      'chua-ba-thien-hau-tra-vinh',
      'chua-ong-vinh-long',
      'chua-luong-xuyen',
      'chua-ky-son-khmer-loan-my',
      'chua-hoi-tong-ben-tre',
      'chua-khmer-vinh-long',
      'chua-bang-trau-song-loc',
      'chua-can-tho-ngu-lac',
      'chua-long-quang-chua-dua',
      'chua-o-mich-ratanadiparamkoskeo',
      'chua-phno-don-chua-giong-lon',
      'chua-phno-om-pung-chua-long-truong',
      'chua-kompong-tung-hung-my',
      'cay-da-cua-huu',
      'dinh-an-hoi',
      'dinh-tan-ngai',
      'dinh-tien-thuy',
      'dinh-hoa-ninh',
      'dinh-hau-thanh',
      'dinh-lang-thien-my',
      'dinh-loc-thuan',
      'dinh-long-duc',
      'dinh-binh-hoa-giong-trom',
      'dinh-vang-quoi',
      'dinh-vinh-xuan',
      'bia-chien-thang-loc-thuan',
      'bia-chien-thang-thanh-phuoc',
      'di-san-duong-dai-mang-thit',
      'bao-tang-tinh-vinh-long',
      'dinh-mieu-con-trung',
      // 40 Heritage Culinary Dishes & Traditional Restaurants (Batch 10)
      'banh-canh-bot-xat',
      'banh-canh-chu-bay-giong-trom-ben-tre',
      'banh-canh-cho-ben-tre-hang-goc-cho-ben-tre-ben-tre',
      'banh-bo-nuong-tra-vinh',
      'banh-tet-la-cam',
      'banh-uot-banh-beo-cho-vung-liem-vinh-long',
      'banh-xeo-bien-binh-dai',
      'banh-xeo-cu-lao',
      'banh-xeo-hen-cu-lao-dai',
      'banh-xeo-oc-gao-cho-lach',
      'bi-cuon-ben-tre',
      'bo-to-ba-tri---cac-mon-bo',
      'bo-to-vinh-long',
      'bun-nuoc-leo-cang-long',
      'bun-nuoc-leo-tieu-can',
      'bun-nuoc-leo-tra-cu',
      'bun-nuoc-leo-vinh-long',
      'bun-nuoc-leo-cay-sung-tra-vinh',
      'bun-suong-du-van-tra-vinh',
      'bun-suong-ut-tam-tra-vinh',
      'bun-rieu-cua-cho-mo-cay-ben-tre',
      'ca-bong-kho-nuoc-dua',
      'ca-coc-kho-nuoc-dua',
      'ca-keo-kho-to',
      'ca-lang-ho-nhung-giam',
      'ca-keo-nuong-ong-say',
      'ca-khoai-tra-vinh',
      'canh-chua-ca-linh',
      'chao-cua-dong',
      'chao-ech-tran-nam',
      'chu-u-rang-me',
      'banh-phu-the-vinh-long',
      'com-dua-com-trai-dua',
      'com-dep-ngoc-bien',
      'goi-cu-hu-dua-tom-thit',
      'hu-tieu-soi-no-cong',
      'hu-tieu-ba-phu',
      'oc-gao-cu-lao-dai',
      'oc-len-xao-nuoc-cot-dua',
      'tom-hap-nuoc-dua',
      // 40 OCOP Specialties & Local Terroir Crafts (Batch 11)
      'lang-gach-gom-mang-thit',
      'lang-nghe-gach-gom-mang-thit-vuong-quoc-do',
      'nha-gom-tu-buoi',
      'lang-nghe-lam-tau-hu-ky',
      'lang-nghe-det-chieu-ca-hom-ben-ba',
      'lang-nghe-dan-non-la-tt-long-ho',
      'lang-nghe-tom-kho-vinh-kim',
      'lang-nghe-tieu-thu-cong-nghiep-tre-ham-giang-co-so-tri-canh',
      'lang-mai-vang-phuoc-dinh',
      'cong-ty-tnhh-tra-vinh-farm-sokfarm',
      'lang-nghe-truyen-thong-phu-le',
      'lang-nghe-hoa-kieng-thanh-tan',
      'lang-nghe-bo-choi-my-an',
      'lang-nghe-chi-xo-dua-khanh-thanh-tan',
      'lang-nghe-dan-dat-dai-an',
      'lang-nghe-thach-dua-hung-phong',
      'lang-nghe-thu-cong-my-nghe-dua-mo-cay-nam',
      'lang-nghe-dong-ghe-xuong-an-dinh',
      'lang-nghe-che-tac-mat-na-khmer-nguyet-hoa',
      'lang-banh-trang-tra-on',
      'buoi-da-xanh',
      'tep-kho-my-long',
      'ruou-truyen-thong-cuu-long-cuu-long-my-tuu',
      'dua-luoi-truong-long-hoa',
      'chom-chom-cau-ke',
      'nuoc-khoang-thien-nhien-sao-bien-starfiwa',
      'banh-kep-thuy-kieu',
      'banh-tet-tu-quy-hai-ly',
      'bun-tuoi-an-dao',
      'buoi-da-xanh-giong-trom',
      'ca-bong-lau-mot-nang-binh-dai',
      'ca-kho-dac-san-thanh-phong-ocop',
      'cua-bien-va-ngheu-thanh-phu',
      'cu-cai-muoi-chit-sa',
      'dua-sap-hoa-tan',
      'gao-huu-co-long-hoa-hoa-minh-ocop-4-sao',
      'hoa-cuc-mam-xoi-long-thoi',
      'keo-dua-tuyet-phung',
      'lap-xuong-ngoc-huong',
      'mat-ong-rung-ban-my-long-nam',
      // 40 Accommodations, Eco-Resorts & Travel Experiences (Batch 12)
      'binh-minh-ecolodge-riverside',
      'khu-du-lich-somo-farm-cuu-long',
      'homestay-cu-lao-dai',
      'coco-riverside-lodge-trung-nghia',
      'mekong-homestay-viet-nam',
      'du-lich-sinh-thai-cu-lao-may-nam-khanh',
      'khu-du-lich-sinh-thai-nam-son',
      'resort-vinh-sang',
      'homestay-co-chin-an-binh',
      'homestay-con-ba-tu',
      'nha-dua-cocohome',
      'tra-vinh-palace-hotel',
      'khach-san-diamond-stars',
      'mekong-hotel-restaurant',
      'lo-lem-homestay',
      'van-trang-hotel',
      'hotel-phuoc-thinh',
      'khach-san-hoang-khiem',
      'homestay-hai-cuong',
      'khach-san-binh-minh',
      'cheo-xuong-rach-an-binh',
      'lam-banh-dan-gian',
      'mua-trai-cay-chin-roi',
      'mua-nuoc-noi-dbscl',
      'khu-sinh-thai-nha-xua-long-ho',
      'khu-du-lich-sinh-thai-hoang-hao',
      'nghe-don-ca-tai-tu',
      'tham-chua-khmer',
      'peace-farm',
      'du-lich-vuon-chu-7-gat',
      'nha-vuon-tu-hien',
      'vuon-dua-sinh-thai-cau-ke-tra-vinh',
      'cu-lao-tan-quy-cang-long-tra-vinh',
      'du-lich-sinh-thai-bien-thanh-phu',
      'du-lich-sinh-thai-san-chim-vam-ho-trai-nghiem-thuyen-rung',
      'xuong-thu-cong-cocohand-vuon-dua-huu-co',
      'con-ngheu-my-long',
      'con-thanh-long',
      'khu-bao-ve-canh-quan-rung-ngap-man-thanh-phu',
      'rung-ngap-man-hiep-thanh-duyen-hai-tra-vinh',
      // 40 Historical & Cultural Relics, Temples, Pagodas & Shrines (Batch 13)
      'bao-tang-van-hoa-dan-toc-khmer-tinh-tra-vinh',
      'chua-hang',
      'dinh-tan-hoa-w3',
      'khu-mo-than-nhan-thoai-ngoc-hau',
      'lang-ong-nam-hai',
      'dinh-tan-giai',
      'lang-ong-con-tau',
      'lau-ba-mieu-ba-chua-xu-ba-co-hy',
      'lang-mo-va-khu-tuong-niem-nguyen-dinh-chieu',
      'chua-tuyen-linh-mo-cay-nam',
      'di-tich-lich-su-dong-khoi-my-long',
      'lang-ong-nam-hai-binh-thang',
      'mieu-ba-chua-xu-tan-quy',
      'nha-co-cau-ke',
      'nha-tho-duc-my-cho-cua',
      'bao-tang-tinh-ben-tre',
      'chua-an-linh',
      'chua-can-snom-can-nom',
      'chua-giac-linh-chua-doi',
      'chua-sa-leng-kompong-chray',
      'chua-sam-pua',
      'chua-troprasbat-chua-chong-bat',
      'chua-tuyen-linh-mo-cay-bac',
      'chua-vam-ray-chua-phat-nam',
      'den-tho-trung-tuong-dong-van-cong',
      'dinh-trung-my',
      'di-tich-cay-da-doi',
      'di-tich-khao-co-luu-cu-ii',
      'duong-ho-chi-minh-tren-bien-ben-xuat-phat-thanh-phong',
      'chua-krapoumchhouk-chral-chua-cha',
      'khu-luu-niem-nguyen-thi-dinh',
      'khu-mo-nha-giao-vo-truong-toan',
      'lau-ba-co-hy-thuong-dong-nuong-nuong',
      'mieu-ba-chua-xu-tra-vinh',
      'mo-va-khu-luu-niem-vo-truong-toan',
      'cong-vien-an-hoi',
      'nha-gom-tu-buoi-w3',
      'khu-du-lich-bien-con-bung',
      'khu-du-lich-cho-noi-tra-on',
      'nha-tho-mac-bac-tieu-can',
      // 40 Traditional Restaurants, Specialty Cafes & Refreshment Spots (Batch 14)
      'son-hao---hai-san',
      'mut-dua-sap-cau-ke',
      'oc-viet-ben-tre',
      'deja-huynh-kha-coffee',
      'he-thong-102-coffee-shop',
      'deja-vu-cafe',
      'tau-hu-nong',
      'pho-nuong-bien-dong---pham-thai-buong',
      'coc-cafe---pham-ngu-lao',
      'snowy---kem-cafe',
      'hu-tieu---sui-cao',
      'mai-la---quan-nuong-ngoi',
      'quan-chao-luon-ba-nam-cho-vinh-long',
      'quan-com-175-ben-tre',
      're-tranhcom---2-thang-9',
      'bun-suong',
      'ngua-hoang-food-beer',
      'robusta-cafe---tran-dai-nghia',
      'ninh-kieu-5---quoc-lo-60',
      'kem-xoi-dua---khu-sao-mai',
      'com-tam-co-tuyet',
      'bun-mam-co-ba',
      'ba-ba---banh-flan',
      'the-hotpot---lau-1-nguoi',
      'lemais---coffee-tea',
      'nam-son',
      'hoa-su-coffee',
      'pho-lu-hai',
      'hu-tieu-chay',
      'ben-dua-quan---lau-ga-noi',
      '1983-coffee-pizza',
      'bun-rieu-cua-thao-my',
      'dimsum-quan-nhat---am-thuc-trung-hoa',
      'nha-hang-huong-sen',
      'nha-hang-am-thuc-pho',
      'nha-hang-sau-tu',
      'nha-hang-song-thao',
      'khuc-ban-chieu',
      'robusta-koi-garden',
      'banh-bao-tai-co',
      // 40 Traditional Festivals, Cultural Events & Scenic Wonders (Batch 15)
      'tet-doan-ngo',
      'le-hoi-ngu-dan-thanh-hai-le-hoi-cau-ngu',
      'le-hoi-nguyen-tieu-o-tra-cu',
      'le-via-ba-co-hy',
      'hoi-thi-don-ca-tai-tu-cai-luong-huyen-long-ho',
      'hoi-cho-xuc-tien-thuong-mai-du-lich-vinh-long-dip-tet-nguyen-dan-vinh-long',
      'ngay-hoi-thanh-tra',
      'tet-nguyen-dan-mien-tay',
      'le-vu-lan',
      'le-gio-to-hung-vuong',
      'hoi-cho-thuong-mai-cay-giong-hoa-kieng-cho-lach',
      'le-ha-dien-dinh-tan-hoa',
      'le-thuong-dien-dinh-tan-ngai',
      'hoi-thi-giong-ca-cai-luong-ut-tra-on',
      'ngay-hoi-trai-cay',
      'le-hoi-cau-ngu',
      'le-hoi-long-den',
      'tuan-le-van-hoa-the-thao-va-du-lich-tinh-vinh-long-vinh-long',
      'hoi-cho-xuc-tien-thuong-mai-san-pham-cong-nghiep-nong-thon-va-ocop-vinh-long-gan-voi-ok-om-bok-vinh-long',
      'hoi-cho-dac-san-vung-mien-khu-vuc-dbscl-vinh-long-vinh-long',
      'hoi-cho-thuong-mai-du-lich-ben-tre-ben-tre',
      'hoi-cho-thuong-mai-du-lich-tinh-tra-vinh-tra-vinh',
      'hoi-thi-san-pham-ocop-va-dac-san-ben-tre-ben-tre',
      'tuan-le-du-lich-tra-vinh-kham-pha-xu-dua-tra-vinh',
      'giai-ban-marathon-vinh-long-mo-rong-hanh-trinh-trai-tim-mekong-vinh-long',
      'giai-vo-dich-xe-dap-tinh-vinh-long-mo-rong-vinh-long',
      'giai-marathon-ben-tre-xu-dua-ben-tre',
      'giai-marathon-tra-vinh-tra-vinh-marathon-tra-vinh',
      'trien-lam-hoi-cho-nong-nghiep-cong-nghe-cao-ben-tre-ben-tre',
      'giai-dua-ghe-ngo-truyen-thong-tinh-ben-tre-ben-tre',
      'hoi-cho-lua-gao-va-xuc-tien-thuong-mai-du-lich',
      'le-cung-lau-ba-ram-thang-gieng',
      'le-hoi-van-hoa-the-thao-du-lich-dong-bao-khmer-nam-bo-tinh-tra-vinh-tra-vinh',
      'giai-the-thao-dan-toc-quoc-phong-tinh-tra-vinh-tra-vinh',
      'lien-hoan-don-ca-tai-tu-nam-bo-tinh-ben-tre-ben-tre',
      'lien-hoan-van-nghe-quan-chung-tinh-tra-vinh-tra-vinh',
      'tuan-le-van-hoa-am-thuc-an-hoi-2026',
      'le-cung-mieu',
      'le-hoi-nguyen-tieu',
      'le-chol-chhnam-thmay',
      // 40 Craft Workshops, Terroir Products & Artisanal Specialties (Batch 16)
      'lang-nghe-san-xuat-chi-xo-dua-an-thanh',
      'lang-nghe-dan-dat-phuoc-tuy',
      'lo-com-cuu-long-vlt',
      'dong-muoi-bao-thanh',
      'lang-dan-luc-binh-ngai-tu',
      'vung-cam-sanh-tra-on',
      'htx-nong-nghiep-thong-hoa-dua-sap',
      'lang-nghe-dan-dat-ba-tri',
      'lang-nghe-det-chieu-ca-hom',
      'lang-nghe-keo-dua-ba-tri',
      'lang-nghe-san-xuat-muoi-bao-thanh',
      'lang-nghe-thu-cong-dua-phuoc-long',
      'lang-nghe-thu-cong-my-nghe-tu-dua-tai-tan-thach',
      'lang-nghe-tieu-thu-cong-nghiep-duc-my',
      'lang-nghe-tieu-thu-cong-nghiep-ham-giang-tre-truc',
      'lang-nghe-tre-truc-ba-tri',
      'vung-trong-dua-sap-cau-ke',
      'lang-hoa-kieng-long-duc-tra-vinh',
      'quyt-duong-cau-ke',
      'lang-banh-trang-giay-tuong-loc',
      'lang-nghe-gom-do-mang-thit',
      'lang-gach-gom-do-mang-thit',
      'lang-keo-dua-phuong-7-ben-tre',
      'lang-dan-lat-duc-my-cang-long',
      'lang-nghe-dan-gio-cong-dua-hung-phong',
      'lang-banh-trang-my-long',
      'dac-san-mam-bo-hoc-tra-cuon',
      'vung-buoi-da-xanh-chau-thanh',
      'lang-nghe-det-chieu-an-hiep',
      'lang-nghe-thu-cong-my-nghe-luc-binh-my-an-vinh-long',
      'lang-nghe-may-tre-dan-dai-an',
      'cong-ty-tnhh-mtv-quoc-thao',
      'nghe-det-luc-binh-vinh-long',
      'lang-nghe-bun-suong',
      'co-so-keo-dua-hong-van',
      'lang-nghe-cay-giong-cho-lach',
      'lang-nghe-det-chieu-ham-tan',
      'lang-nghe-do-go-tre-ham-giang',
      'lang-hoa-mai-binh-hoa-phuoc',
      'lang-nghe-gom-truyen-thong-long-ho',
      // Batch 17: Nature Wonders, Islands & Riverine Eco-Attractions (40 entities)
      'bun-nuoc-leo-cho-ba-tri-ben-tre',
      'hu-tieu-sa-dec-chu-tu-gan-cho-phu-hung-ben-tre',
      'banh-mi-sau-hoa-ben-tre',
      'du-lich-vuon-chu-7-gat-vlt',
      'rach-cau-lau-vinh-long',
      'bien-con-nhan',
      'cua-cung-hau-tra-vinh',
      'cua-dai-cua-song-my-thosong-tien-ben-tre',
      'cua-hang-ocop-tinh-ben-tre-trung-tam-xuc-tien-dau-tu-ho-tro-doanh-nghiep-ben-tre',
      'cu-lao-long-tri',
      'song-hau-doan-cua-dinh-an-tra-vinh',
      'bai-bien-ba-tri',
      'bai-bien-thanh-phu',
      'ben-cat',
      'bien-binh-dai',
      'con-cai-ga',
      'con-ngheu-bai-vang-bien-tra-vinh',
      'con-tan-quy-cu-lao-tan-quy',
      'cua-song-cung-hau-ca-heo-cau-ngang-tra-vinh',
      'cu-lao-an-loc',
      'du-lich-sinh-thai-miet-vuon-mo-cay-bac',
      'khu-bao-ve-canh-quan-thanh-phu-ben-tre',
      'khu-du-lich-sinh-thai-con-thanh-long',
      'khu-du-lich-sinh-thai-nguoi-giu-rung',
      'nha-tho-la-ma-ba-giong',
      'nha-tho-la-ma-den-duc-me-hang-cuu-giup-la-ma',
      'rung-ngap-man-binh-dai',
      'rung-tram-cang-long-tra-vinh',
      'san-chim-chua-phat-lon-tra-vinh',
      'san-chim-vam-ho-ben-tre',
      'song-thom-diem-tham-quan-lang-nghe',
      'vam-tac-thu-rung-ban-song-co-chien-tra-vinh',
      'vuon-cay-an-trai-mo-cay-bac',
      'vuon-chom-chom-ba-ngoi',
      'xa-kim-hoa-diem-du-lich-sinh-thai-song-nuoc',
      'cu-lao-minh',
      'cho-ba-tri',
      'cho-cho-lach',
      'canh-dong-dien-gio-thanh-phu',
      'cua-hang-ocop-tra-vinh-trung-tam-xuc-tien-thuong-mai-tinh-tra-vinh',
      // 40 Historic Relics, Pagodas, Ancient Temples & Cultural Shrines (Batch 18)
      'that-phu-mieu-chua-ong-vinh-long',
      'khu-mo-than-nhan-danh-than-thoai-ngoc-hau',
      'chua-vam-ray-tra-vinh',
      'chua-van-phuoc',
      'thanh-duong-giao-xu-mac-bac',
      'nha-tho-chanh-toa-vinh-long',
      'nha-tho-chanh-toa-ben-tre-ben-tre',
      'nha-tho-chanh-toa-tra-vinh-tra-vinh',
      'nha-tho-cai-mon-ben-tre',
      'nha-tho-kinh-long-hoi',
      'chua-bo-de',
      'chua-co-nodol',
      'chua-hang-cha-lo',
      'chua-ong-met-bodonisaraj',
      'chua-lo-gach',
      'chua-long-khanh',
      'chua-ky-son-ky-son',
      'chua-kompong-ksan',
      'chua-khai-tuong',
      'chua-hung-hue',
      'chua-giong-tranh-wat-kosaleang',
      'chua-kompongrang-wat-kompongro',
      'chua-o-chhuc',
      'chua-giac-linh',
      'chua-phuoc-hau-ngai-tu',
      'chua-phuoc-khanh-chua-phat',
      'chua-quan-am-phuong-8',
      'chua-quan-am-tra-on-mai-am-quan-am',
      'chua-long-thanh-ben-tre',
      'chua-long-buu',
      'chua-phap-hoa',
      'chua-khanh-thanh',
      'chua-hung-lam',
      'chua-hao-tam',
      'chua-gia-kiet',
      'chua-ang-ka-nguol-an-truong',
      'tinh-xa-ngoc-nhan',
      'mieu-ba-chua-xu-vinh-long-vinh-long',
      'mieu-ba-chua-xu-my-hoa-ben-tre',
      'de-an-di-san-duong-dai-mang-thit',
      // 40 Craft Villages & Artisanal Terroir Products (Batch 19 - 100% Craft Village Coverage)
      'lang-nghe-cham-non-la-long-ho',
      'lang-nghe-det-chieu-vung-liem',
      'lang-se-loi-lac-va-dan-lat-vung-liem',
      'lang-nghe-trong-lac-trung-thanh-dong',
      'lang-nghe-dan-chieu-va-lam-banh-xe-may-tre',
      'lang-nghe-banh-trang-tam-binh',
      'lang-nghe-dan-luc-binh-ngai-tu-binh-ninh',
      'lang-nghe-dan-lat-may-tre-phu-le',
      'lang-nghe-dan-lat-an-duc',
      'lang-nghe-dan-chapay-phu-can',
      'lang-tau-hu-ky-my-hoa',
      'htx-cam-sanh-tra-on',
      'co-so-keo-dua-mo-cay',
      'lang-gach-gom-long-ho',
      'lang-nghe-com-dep-ba-so',
      'vung-khoai-lang-binh-tan',
      'lang-nghe-che-bien-hai-san-kho-thanh-phong',
      'lang-nghe-thu-cong-my-nghe-tu-dua-quoi-son',
      'lang-hoa-kieng-va-cay-giong-cho-lach',
      'lang-nghe-nau-ruou-phu-le',
      'cong-ty-co-phan-xuat-nhap-khau-ben-tre-betrimex',
      'cong-ty-tnhh-che-bien-dua-luong-quoi',
      'lang-nghe-dan-non-la-an-hiep',
      'lang-nghe-cay-giong-uon-kieng-hung-khanh-trung',
      'lang-nghe-dan-trang-gio-cong-dua-luong-phu',
      'lang-nghe-banh-trang-nem-cu-lao-may',
      'ca-phi-sa-ot-thanh-phuoc',
      'htx-thuy-san-sinh-thai-thanh-phuoc',
      'cua-hang-ocop-vung-liem',
      'diem-trung-bay-va-ban-san-pham-ocop-vinh-long-tai-ben-cang',
      'ca-doi-kho-mot-nang-binh-dai',
      'dua-kho-tra-vinh',
      'dua-sap-cau-ke-dac-san-ben-tre',
      'dua-sap-tra-vinh',
      'gao-sach-lua-tom-thanh-phu',
      'gao-sach-tom-lua-thanh-phu-ocop',
      'hop-tac-xa-thuy-san-thanh-loi-ngheu-thanh-hai-ocop',
      'keo-dua-mo-cay-co-so-tuyet-phung',
      'kho-ca-bien-thanh-phu',
      'kho-ca-bong-lau-ca-du-do-ca-bong-cat-mot-nang-thanh-phong',
      // 40 Culinary Specialties & Seasonal Events (Batch 20 - 100% Event Coverage)
      'cho-hoa-tet',
      'le-hoi-ba-chua-xu',
      'chao-cua-dong-ben-tre',
      'mam-song-khoai-lang',
      'ca-loc-nuong-trui',
      'nuoc-dua-tuoi-ben-tre',
      'banh-canh-ben-co-tra-vinh',
      'banh-xeo-oc-gao-phu-da',
      'co-diem---banh-canh-vit-bot-xat',
      'oc-lac-hap-la-gung',
      'mam-chung-chuoi-dap',
      'chuot-dua-hap-com',
      'oc-gao-con-phu-da-hap-sa',
      'loi-choi-sa-ot-tra-vinh',
      'hu-tieu-vinh-long',
      'oc-gao-phu-da',
      'oc-gao-vinh-binh',
      'mut-me-cai-von',
      'chuot-dong-nuong',
      'nam-moi-xao',
      'ga-hap-ruou',
      'che-buoi-vinh-long',
      'canh-chua-ca-linh-bong-so-dua',
      'tom-su-nuong-than-binh-dai',
      'hau-sua-thanh-phu',
      'nem-nuong-vinh-long',
      've-sau-chien-gion',
      'loi-choi-sa-ot',
      'xoi-man-69---hung-dao-vuong',
      'yogurt-dua---ba-muoi-thang-tu',
      'dang-ga---cac-mon-ga-ta',
      'banh-flan-14',
      'pho-91',
      'banh-xeo-long-binh-2',
      'banh-cuon-nong---tran-quoc-tuan',
      'com-ga-bong-viet',
      'bun-bo-hue-19',
      '3-mien-tra-vinh---bun-dau-mam-tom',
      'keo-dua-mo-cay-dish',
      'lo-com-cuu-long',
      // 40 Culinary Specialties & Heritage Restaurants (Batch 21 - 100% Dish Coverage)
      'banh-trang-my-long',
      'mam-tom-cha-vinh-long',
      'ca-tai-tuong-chien-xu',
      'banh-xeo-mien-tay',
      'goi-cuon-tom-thit',
      'cha-gio-chay',
      'chao-ca-loc-rau-dang',
      'tom-cang-xanh-nuong',
      'banh-canh-ben-tre',
      'bo-nuong-la-lot',
      'xoi-vi-mien-tay',
      'tom-rang-muoi-ot',
      'bun-mam-mien-tay',
      'bun-bo-co-tam-cho-ben-tre-ben-tre',
      'com-ga-xoi-mo-5-vi-ben-tre',
      'tinh-binh-chay-vinh-long',
      'com-chay-au-lac-vinh-long',
      'duong-dua',
      'tep-rang-dua',
      'nem-nuong-thanh-binh-ben-tre',
      'cua-com-duyen-hai',
      'tom-cang-xanh-song-tien',
      'ba-nhi-bun-bo-hue-vinh-long',
      'prov-1',
      'nha-hang-thien-tan',
      'ma-van-tai-quan---pham-thai-buong',
      'lau-tai-co',
      'lau-bo',
      'lau-mam-ben-tre',
      'tiem-ba-khoang',
      'xom-nuong-que-nha',
      'chuoi-nuong-gia-truyen',
      'khoi---lau-nuong',
      'co-dai---sinh-to-giai-khat',
      'mi-cay-vinh-long',
      'hot-pot-72---quan-lau',
      'caffe-takeaway---tan-ke',
      'vys-house-drinks-tea---2-thang-9',
      'lu-lu---cake-drink',
      'kimchi-kimchi---mi-cay-han-quoc',
      // 40 Accommodations & Cultural Experiences (Batch 22)
      'ks-nh-hung-vuong',
      'khach-san-anh-hong-mang-thit',
      'khach-san-nghia-hiep',
      'khach-san-khoi-hoa',
      'khach-san-duc-dao',
      'khach-san-hoai-phu',
      'nha-nghi-quynh-phuc',
      'nha-hang-phuong-thuy-1',
      'nha-nghi-thanh-thao',
      'nha-nghi-phuong-nam',
      'ba-dong-beach-resort',
      'mekong-lodge-resort',
      'khach-san-cuu-long',
      'khach-san-chieu-hung',
      'khach-san-trung-tinh',
      'khach-san-vin-vinh-long',
      'khach-san-binh-dai',
      'oasis-hotel',
      'vilabasi-hotel',
      'ben-tre-farm-stay',
      'cho-ben-tre',
      'du-lich-sinh-thai-nam-son',
      'quan-tan-tan',
      'buffet-nuong-kachu',
      'quan-pho-91',
      'quan-lau-ga-noi-nha-san',
      'quan-lau-tai-co',
      'quan-met-bun-dau-mam-tom',
      'nhom-bong-hong-vang',
      'cau-lac-bo-du-lich-cuu-long',
      'cau-lac-bo-trung-tam-van-hoa-thong-tin-vinh-long',
      'quan-buffet-lau-nuong-kachu',
      'com-nieu-nam-bo',
      'nghe-thuat-hat-boi-tinh-vinh-long',
      'cau-lac-bo-don-ca-tai-tu-huyen-vung-liem',
      'cau-lac-bo-don-ca-tai-tu-huyen-long-ho',
      'cau-lac-bo-don-ca-tai-tu-huyen-tam-binh',
      'cau-lac-bo-don-ca-tai-tu-huyen-tra-on',
      'cau-lac-bo-don-ca-tai-tu-huyen-mang-thit',
      'cau-lac-bo-don-ca-tai-tu-thi-xa-binh-minh',
      // 40 Homestays & Immersive Experiences (Batch 23)
      'malis-hotel-tra-vinh',
      'vila-basi',
      'happy-family-guesthouse',
      'coco-happy-farm',
      'coco-farmstay',
      'my-cam-hotel',
      'ba-linh-homestay',
      'mekong-riverside-homestay',
      'cuu-long-hotel',
      'coco-homestay',
      'khach-san-ngoc-quy',
      'green-river-homestay',
      'diamond-stars-ben-tre-hotel',
      'khach-san-thanh-binh-i',
      'khach-san-ngu-long',
      'khach-san-minh-khue',
      'khach-san-ngoc-hung',
      'khach-san-thanh-binh-ii',
      'khach-san-phuong-hoang',
      'khach-san-phung-hoang',
      'cau-lac-bo-don-ca-tai-tu-tinh-vinh-long',
      'mua-chan',
      'cho-noi-tra-on',
      'don-ca-tai-tu-nam-bo',
      'somo-farm-cuu-long-mang-thit',
      'khu-du-lich-sinh-thai-vinh-sang-cu-lao-an-binh',
      'khu-du-lich-sinh-thai-truong-huy-vinh-long',
      'tour-nha-gom-tat-muong-bat-ca',
      'tour-vuong-quoc-gach-ngoi-mang-thit',
      'tour-dem-miet-vuon-vinh-long',
      'tour-cai-thia-lang-xoai-cat-hoa-loc',
      'khu-du-lich-truong-huy-long-ho',
      'khu-am-thuc-pho-cho-phu-khuong',
      'lang-van-hoa-du-lich-cho-lach',
      'trai-nghiem-cau-ca-cau-tom-song-hau',
      'tour-dap-xe-kham-pha-lo-gach-mang-thit',
      'quan-ca-phe-nha-gach-gom-duong-dai',
      'thu-hoach-dua-mo-cay',
      'ngam-binh-minh-co-chien',
      'dap-xe-miet-vuon',
      // 40 Experiences & Natural Landscapes (Batch 24 - 100% Experience Coverage)
      'tham-lo-gach-mang-thit',
      'trai-nghiem-mua-nuoc-noi',
      'quan-meo-u-kitchen',
      'vuon-trai-cay-6-tan-cu-lao-an-binh',
      'khu-sinh-thai-gio-duoc-thanh-phu-ben-tre',
      'mot-ngay-lam-nong-dan',
      'xem-hat-boi',
      'dap-xe-cu-lao',
      'cau-ca-miet-vuon',
      'hoc-nau-an-mien-tay',
      'tat-muong-bat-ca',
      'tham-lo-gach-co',
      'dan-la-dua',
      'tam-song',
      'nau-ruou-dua',
      'di-ghe-tam-ban',
      'tham-lang-hoa-cho-lach',
      'meo-u-kitchen-vinh-long',
      'di-cho-dem-vinh-long',
      'hoc-lam-banh-trang',
      'vuot-song-co-chien',
      'hai-chom-chom-an-binh',
      'tham-quan-vuon-cam-tra-on',
      'lam-keo-dua-mo-cay',
      'nhom-truong-an',
      'don-ca-tai-tu-o-vinh-long',
      'dua-ghe-ngo',
      'cho-tra-vinh',
      'cau-lac-bo-don-ca-tai-tu-truong-xay-dung-mien-tay',
      'co-so-san-xuat-peace-farm',
      'tham-quan-vuon-trai-cay',
      'lam-gom-mang-thit',
      'cheo-xuong-ba-la',
      'du-lich-sinh-thai-cong-dong-thanh-phong-ben-tre',
      'cho-dau-moi-nong-san-ba-cang-song-phu',
      'khu-bao-ton-thien-nhien-thanh-phu',
      'con-bung',
      'cu-lao-tan-quy-cau-ke',
      'cu-lao-may-tra-on',
      'cay-goi-nuoc-di-san-ben-tre',
      // 40 Accommodations & Natural Landscapes (Batch 25 - Over 50% Coverage Milestone)
      'khach-san-lac-long',
      'khach-san-ngoc-trang',
      'khach-san-hoa-ngoc',
      'khach-san-anh-hong',
      'khach-san-khanh-quynh',
      'khach-san-van-trang',
      'khach-san-tan-hung',
      'khach-san-dong-quan',
      'khach-san-thien-thanh',
      'khach-san-loc-phuc',
      'khach-san-ngoc-tram',
      'khach-san-anh-duc',
      'khach-san-phuong-thao',
      'khach-san-truong-an',
      'khach-san-hoang-hao',
      'khach-san-hong-phuong',
      'khach-san-gia-hoa-ii',
      'khach-san-kim-chi-hoang-gia',
      'khach-san-tai-nguyen',
      'khach-san-ban-me',
      'long-ho',
      'song-long-binh',
      'canh-dong-dieu-tra-vinh',
      'cu-lao-may',
      'khu-du-lich-sinh-thai-huynh-kha',
      'bien-con-bung-thanh-phu',
      'cu-lao-an-binh',
      'cu-lao-dai-vung-liem',
      'san-chim-vam-ho',
      'khu-du-lich-truong-huy',
      'ho-truc-giang',
      'con-phu-da',
      'bien-con-bung',
      'cu-lao-dai',
      'con-oc',
      'con-tien',
      'con-ho',
      'nha-xua-cai-cuong',
      'con-ngheu',
      'song-long-ho-vinh-long',
      // 40 Accommodations (Batch 26)
      'khach-san-phuoc-hung',
      'khach-san-an-khang',
      'khach-san-ba-duc',
      'khach-san-ngoc-yen',
      'khach-san-vinh-sang',
      'khach-san-nhat-phuong',
      'khach-san-thanh-xuan',
      'le-thi-thuy-an-homestay',
      'khach-san-bich-ngoan',
      'nha-khach-vinh-tra',
      'khach-san-sanh-phuc',
      'khach-san-hai-duong-2',
      'khach-san-tuong-vy',
      'farmstay-dat-cu-lao',
      'khach-san-huynh-thao',
      'khach-san-dai-an',
      'coco-riverside-lodge',
      'cocohut-homestay',
      'ks-nha-co-cau-ke',
      'nh-ks-sy-dien',
      'homestay-ut-trinh-con-tam-hiep',
      'coconut-homestay',
      'one-hotel',
      'the-grand-hotel-vinh-long',
      'nha-thuyen-nam-cao-homestay',
      'khach-san-phu-gia',
      'coco-home',
      'khach-san-tan-xuan',
      'nha-nghi-dl-sinh-thai-hoang-hao',
      'khach-san-xuan-huong',
      'khach-san-tan-sang',
      'can-tho-hotel-transit',
      'khach-san-paris-vinh-long',
      'resort-ben-tre-riverside',
      'vin-hotel-vinh-long',
      'saigon-vinh-long-hotel',
      'khach-san-ngoi-sao',
      'khach-san-tan-an-loc',
      'muoi-quynh-homestay',
      'homestay-hoa-thanh',
      // 8 Accommodations & 32 Nature Entities (Batch 27 - 100% Accommodation Milestone)
      'hoan-my-homestay',
      'khach-san-tan-thanh-2',
      'khach-san-tan-thanh-6',
      'phuoc-thanh-iv-tourist-area',
      'khach-san-phuoc-thanh-iv',
      'khach-san-nguyen-mai',
      'khach-san-thanh-nguyen',
      'khach-san-hoan-my-2',
      'rach-cai-ca-vinh-long',
      'kenh-tra-on-vinh-long',
      'rach-tra-ngoa-vinh-long',
      'kenh-thay-cai-vinh-long',
      'song-ham-luong-ben-tre',
      'song-ba-lai-ben-tre',
      'rach-gam-ben-tre',
      'song-thom-rach-thom-ben-tre',
      'kenh-bong-bot-tra-vinh',
      'con-ho-oc-dao-xanh-song-co-chien',
      'vuon-chim-hai-chia-tan-my-tra-on',
      'san-chim-vam-ho-ba-tri',
      'cong-vien-dan-chu',
      'canh-dong-mon-an-quang-huu',
      'vung-trong-cam-sapota-huu-thanh',
      'vuon-thanh-tra-dong-thanh',
      'vuon-cay-an-trai-miet-vuon-long-ho',
      'vuon-trai-cay-dac-san-long-ho',
      'cu-lao-an-binh-bao-gom-xa-dong-phu',
      'song-co-chien-doan-mang-thit',
      'vuon-trai-cay-cu-lao-dai',
      'khu-du-lich-sinh-thai-sala',
      'cu-lao-may-cu-lao-luc-si-thanh',
      'cu-lao-tam-hiep',
      'vuon-dua-xiem-xanh-ap-thanh-hoa-1',
      'rung-ngap-man-long-vinh-duyen-hai',
      'vung-giong-cat-long-vinh',
      'khu-du-lich-sinh-thai-vung-dao-duyen-hai',
      'bai-tam-con-phu-binh',
      'khu-bao-ton-oc-gao-vinh-binh',
      'con-du-lich-cai-ga',
      'khu-bao-ton-thien-nhien-dat-ngap-nuoc-vam-ho',
      // 20 Nature Sites & 20 Cafes (Batch 28 - 100% Nature Milestone & 1,000+ Photos)
      'bien-an-thuy',
      'bai-bien-ba-dong',
      'con-phu-da-song-co-chien-cho-lach-ben-tre',
      'bien-thua-duc',
      'vuon-buoi-xanh-vietgap-tu-o',
      'bien-con-bung-thanh-phu-ben-tre',
      'khu-bao-ton-oc-gao-phu-da',
      'con-oc-giong-trom-ben-tre',
      'song-lang-the-tra-vinh',
      'bai-boi-rung-ngap-man-ba-tri-ben-tre',
      'rung-ngap-man-thanh-phong',
      'con-nhan-bien-ba-tri-ben-tre',
      'song-co-chien-vinh-long',
      'song-mang-thit-vinh-long',
      'di-san-duong-dai-mang-thit-tuyen-sinh-thai-kenh-thuy-lo',
      'bien-thoi-thuan',
      'con-quy',
      'vuon-dua-sap-cau-ke-phong-thanh',
      'vung-chuyen-canh-sau-rieng-cu-lao-quoi-an',
      'vung-nuoi-so-huyet-tom-quang-canh-thanh-tri',
      'ct-quan---mon-nuong-coffee',
      'ohana-milktea-coffee',
      'green-coffee---tran-dai-nghia',
      'panda-purple-cafe',
      'yolo-coffee',
      'catimo-coffee',
      'coi-xua-cafe---pham-thai-buong',
      'lang-van-coffee',
      'anns-coffee',
      'ixigo-coffee',
      'cat-tuong---the-coffee-house',
      'cafe-de-paris---pham-ngu-lao',
      '1985-cafe',
      'mandi-cafe',
      'choosa-damour---coffee-flowers',
      'tra-sua-baam-cha',
      'tra-sua-huy',
      'pho-xanh-garden-coffee',
      'monkey-tea---tra-sua-coffee',
      'tra-sua-rom-149',
      // 27 Cafes & 13 Restaurants (Batch 29 - 100% Cafe Milestone & 60% Platform Coverage)
      'gazebo-cafe',
      'che-ba-cam-khu-vuc-cho-ben-tre-ben-tre',
      'ca-phe-xua-tra-vinh',
      'ca-phe-song-tien-ben-ninh-kieu-vinh-long-vinh-long',
      'ca-phe-vuon-cau-khu-con-phung-con-phuoc-vinh-long',
      'ca-phe-highland-vincom-vinh-long-vinh-long',
      'quan-che-ba-tu-cho-vinh-long-vinh-long',
      'kem-dat-vinh-long-khu-cau-lau-vinh-long',
      'sinh-to-ha-tien-duong-pham-thai-buong-vinh-long',
      'che-khuc-bach-khu-dem-vinh-long-cho-dem-phuong-1-vinh-long',
      'quan-che-ba-hai-cho-tra-vinh',
      'ca-phe-bo-song-tra-vinh',
      'quan-che-banh-lot-khmer-gan-ao-ba-om-tra-vinh',
      'ca-phe-vuon-dua-tra-vinh',
      'quan-kem-sinh-to-thanh-binh-tra-vinh',
      'tiem-banh-che-gan-chua-ang-angkor-borei-tra-vinh',
      'ca-phe-cay-bang-phuong-4-tra-vinh',
      'quan-sinh-to-nuoc-ep-cho-dem-tra-vinh',
      'ca-phe-ho-sen-tra-vinh',
      'zen-coffee',
      'khoi-nguyen-coffee---hung-dao-vuong',
      'henry-coffee',
      'brownie-coffee-and-tea',
      'bin-coffee',
      'tra-sua-tapi---trung-nu-vuong',
      'tra-sua-family---dong-khoi',
      'full-house-coffee',
      'ut-an---vuon-am-thuc',
      'am-thuc-chay-ta-on---duong-so-2',
      'lang-be---am-thuc-du-lich-sinh-thai',
      'quan-71---am-thuc-chay-xoi-che',
      'nha-hang-lang-chai',
      'song-nuoc-mien-tay-restaurant---am-thuc-mien-tay',
      'hu-tieu-xi-quach-a-linh---le-loi',
      'bun-nuoc-leo---ly-thuong-kiet',
      'bun-nuoc-leo-huong-tra---pham-ngu-lao',
      'quan-tuyet---com-ca-ri-ga',
      'de-nhat-lau-ca-keo---quan-an-gia-dinh',
      'chau-dong-quan---am-thuc-viet',
      'quan-tom-cang-xanh-hai-lua-cu-lao-an-binh-vinh-long',
    ]

    expect(documentaryIds.length).toBe(1064)

    for (const id of documentaryIds) {
      const row = db.prepare(`SELECT id, images, attributes FROM entities WHERE id = ?`).get(id) as { id: string; images: string; attributes: string }
      expect(row, `Entity ${id} must exist in DB`).toBeDefined()

      const images = JSON.parse(row.images)
      expect(images[0]).toBe(`/img/entities/${id}.webp`)

      const attrs = JSON.parse(row.attributes || '{}')
      expect(attrs.image_author, `Entity ${id} must have author`).toBeDefined()
      expect(attrs.image_author.length).toBeGreaterThan(1)
      expect(attrs.image_source, `Entity ${id} must have publication source`).toBeDefined()
      expect(attrs.image_source.length).toBeGreaterThan(1)
      expect(attrs.image_type).toBe('documentary')
      expect(attrs.is_verified_photo).toBe(true)

      const assetPath = path.join(publicImgDir, `${id}.webp`)
      expect(fs.existsSync(assetPath), `WebP for ${id} must exist locally`).toBe(true)
      const stat = fs.statSync(assetPath)
      expect(stat.size, `WebP for ${id} must be > 1KB`).toBeGreaterThan(1024)
    }
  })

  it('verifies artisanal terroir visual engine generates valid SVG with river waves and watermark', () => {
    const categories = ['attraction', 'history', 'craft', 'dish', 'nature', 'itinerary']
    
    for (const cat of categories) {
      const bgValue = generateCategoryPlaceholder(`item-${cat}`, cat)
      expect(bgValue.startsWith("url('data:image/svg+xml,")).toBe(true)
      expect(bgValue.endsWith("')")).toBe(true)

      const encoded = bgValue.slice("url('data:image/svg+xml,".length, -2)
      const svg = decodeURIComponent(encoded)

      // Must be valid SVG structure
      expect(svg).toContain('<svg')
      expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"')
      expect(svg).toContain('viewBox="0 0 400 240"')
      expect(svg).toContain('</svg>')

      // Must include Alluvial Mekong River wave paths
      expect(svg).toContain('M0,')
      expect(svg).toContain('L400,240 L0,240 Z')

      // Must include Cultural Typography Watermark
      expect(svg).toContain('BẢN SẮC NAM BỘ')
    }
  })

  it('verifies category-specific terroir motifs are rendered in SVG', () => {
    // Craft category should render Mang Thit kiln dome outline (stroke-dasharray="4 3")
    const craftBg = generateCategoryPlaceholder('craft-test', 'craft')
    const craftSvg = decodeURIComponent(craftBg.slice("url('data:image/svg+xml,".length, -2))
    expect(craftSvg).toContain('stroke-dasharray="4 3"')

    // Attraction / history should render heritage pagoda eave arc
    const attractionBg = generateCategoryPlaceholder('attraction-test', 'attraction')
    const attractionSvg = decodeURIComponent(attractionBg.slice("url('data:image/svg+xml,".length, -2))
    expect(attractionSvg).toContain('C190,68 270,68 350,40')

    // Itinerary should render exploration trail waypoint curve
    const itineraryBg = generateCategoryPlaceholder('itinerary-test', 'itinerary')
    const itinerarySvg = decodeURIComponent(itineraryBg.slice("url('data:image/svg+xml,".length, -2))
    expect(itinerarySvg).toContain('stroke-dasharray="5 4"')
  })
})
