"""Render the reviewed Nginx ingress for a concrete runtime topology.

The checked-in configs are the Compose form.  Compose keeps optional agent and
bot DNS lookups request-time; the systemd form replaces those names with the
loopback listeners owned by the systemd units.  Rendering is deliberately
textual and deterministic so the generated bytes can be included in launch
evidence and reviewed before installation.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


TOPOLOGIES = {"compose", "systemd"}


def render_config(source: str, *, topology: str) -> str:
    """Return ``source`` rendered for ``topology``.

    Compose is the canonical source form.  Systemd rendering removes the
    Docker resolver and replaces every internal service target with its
    loopback listener; no Docker hostname may leak into the result.
    """

    if topology not in TOPOLOGIES:
        raise ValueError(f"unsupported Nginx topology: {topology!r}")
    if topology == "compose":
        return source

    rendered = source
    # URI-less proxy_pass preserves the original raw path/query.  When an
    # admin rewrite runs first, Nginx forwards the rewritten URI with the same
    # query string without constructing it from normalized variables.
    for compose_target, systemd_target in (
        ("$agent_upstream$request_uri", "http://127.0.0.1:8360"),
        ("$agent_upstream$uri$is_args$args", "http://127.0.0.1:8360"),
        ("$bot_upstream$request_uri", "http://127.0.0.1:8361"),
        ("$bot_upstream$uri$is_args$args", "http://127.0.0.1:8361"),
    ):
        rendered = rendered.replace(
            f"proxy_pass {compose_target};",
            f"proxy_pass {systemd_target};",
        )
    rendered = re.sub(r"^\s*set \$(?:agent|bot)_upstream [^;]+;\r?\n", "", rendered, flags=re.MULTILINE)
    rendered = rendered.replace("resolver 127.0.0.11 valid=5s ipv6=off;\n", "")
    rendered = rendered.replace("server nuxt:3000;", "server 127.0.0.1:3000;")
    rendered = rendered.replace("http://vl360_nuxt", "http://127.0.0.1:3000")
    if "$agent_upstream" in rendered or "$bot_upstream" in rendered:
        raise ValueError("systemd Nginx render contains an unsupported variable upstream")
    if any(host in rendered for host in ("agent:", "bot-gateway:", "nuxt:")):
        raise ValueError("systemd Nginx render contains a Docker service hostname")
    return rendered


def render_file(source_path: Path, destination: Path, *, topology: str) -> None:
    rendered = render_config(source_path.read_text(encoding="utf-8"), topology=topology)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(destination.name + ".tmp")
    temporary.write_text(rendered, encoding="utf-8", newline="\n")
    temporary.replace(destination)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--topology", choices=sorted(TOPOLOGIES), required=True)
    parser.add_argument("--input", type=Path, help="single source config")
    parser.add_argument("--output", type=Path, help="single rendered config")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output-dir", type=Path, help="render nginx.conf and nginx-ssl.conf")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if (args.input is None) != (args.output is None):
        raise SystemExit("--input and --output must be supplied together")
    if args.input is None and args.output_dir is None:
        raise SystemExit("supply --input/--output or --output-dir")
    if args.input is not None:
        render_file(args.input, args.output, topology=args.topology)
    else:
        for name in ("nginx.conf", "nginx-ssl.conf"):
            render_file(args.root / name, args.output_dir / name, topology=args.topology)
    return 0


if __name__ == "__main__":
    sys.exit(main())
