-- Data verification P0 fixes generated by scripts/generate_data_verification_report.py
-- Run a backup before applying. These statements quarantine confirmed factual errors;
-- they intentionally do not invent replacement descriptions.

BEGIN;

-- hu-tieu-my-tho: DB gán origin='Vĩnh Long' và area='vinh-long' cho Hủ tiếu Mỹ Tho.
-- Truth/source: Hủ tiếu Mỹ Tho là món do người Mỹ Tho chế biến; Mỹ Tho thuộc Tiền Giang cũ, ngoài 3 legacy areas. (https://vi.wikipedia.org/wiki/H%E1%BB%A7_ti%E1%BA%BFu_M%E1%BB%B9_Tho)
UPDATE entities SET status = 'needs_fact_review', verified = 0 WHERE id = 'hu-tieu-my-tho';

-- banh-cong-soc-trang: DB gán origin='Trà Vinh' và area='tra-vinh' cho Bánh cống Sóc Trăng.
-- Truth/source: Nguồn báo chí mô tả bánh cống là đặc sản/nguyên gốc Sóc Trăng cũ. (https://vnexpress.net/banh-cong-dac-san-cua-nguoi-khmer-o-soc-trang-4523101.html)
UPDATE entities SET status = 'needs_fact_review', verified = 0 WHERE id = 'banh-cong-soc-trang';

-- chua-sa-lon-chua-chen-kieu: DB đặt Chùa Sà Lôn/Chùa Chén Kiểu ở Phường Trà Vinh, Trà Vinh và architectural_style='Chùa Việt'.
-- Truth/source: Chùa Sà Lôn/Chùa Chén Kiểu là chùa Khmer Nam tông ở khu vực Sóc Trăng cũ, nay thuộc Cần Thơ sau sáp nhập; không thuộc legacy Trà Vinh. (https://vi.wikipedia.org/wiki/Ch%C3%B9a_S%C3%A0_L%C3%B4n)
UPDATE entities SET status = 'needs_fact_review', verified = 0 WHERE id = 'chua-sa-lon-chua-chen-kieu';

-- chien-thang-giong-dua-giong-trom: DB đặt Di tích lịch sử Chiến thắng Giồng Dứa ở Bến Tre và phần mô tả lại nói về mộ hợp chất Chợ Lách.
-- Truth/source: Nguồn báo chí địa phương mô tả Di tích lịch sử Chiến thắng Giồng Dứa là di tích cấp quốc gia của tỉnh Tiền Giang; nội dung mộ hợp chất Chợ Lách không khớp với tên entity. (https://tintucmientay.baoangiang.com.vn/tien-giang-chien-thang-giong-dua-lam-chan-dong-du-luan-trong-va-ngoai-nuoc-a361124.html)
UPDATE entities SET status = 'needs_fact_review', verified = 0 WHERE id = 'chien-thang-giong-dua-giong-trom';

-- chua-ong-met-botum-vong-sa-som-rong: DB gộp tên Chùa Ông Mẹt với 'Botum Vong Sa Som Rong' và đặt architectural_style='Chùa Hoa'.
-- Truth/source: Chùa Ông Mẹt ở Trà Vinh là chùa Khmer Nam tông, còn Bô Tum Vông Sa Som Rông/Som Rong là một chùa Khmer khác ở Sóc Trăng/Cần Thơ mới. (https://vovworld.vn/vi-VN/viet-nam-dat-nuoc-con-nguoi/chua-ong-met-di-tich-cap-quoc-gia-o-tinh-tra-vinh-2004638.vov5)
UPDATE entities SET status = 'needs_fact_review', verified = 0 WHERE id = 'chua-ong-met-botum-vong-sa-som-rong';

-- khu-bao-ton-lung-binh-hoa-tra-vinh: DB tạo entity 'Khu bảo tồn thiên nhiên Lung Bình Hòa' ở Trà Vinh nhưng summary/description lại nói về Khu bảo tồn thiên nhiên Lung Ngọc Hoàng ở Hậu Giang.
-- Truth/source: Khu bảo tồn thiên nhiên Lung Ngọc Hoàng là một thực thể khác, nằm ở vùng Hậu Giang/Cần Thơ mới; nội dung hiện tại không chứng minh sự tồn tại của 'Lung Bình Hòa' tại Trà Vinh. (https://vi.wikipedia.org/wiki/Khu_b%E1%BA%A3o_t%E1%BB%93n_thi%C3%AAn_nhi%C3%AAn_Lung_Ng%E1%BB%8Dc_Ho%C3%A0ng)
UPDATE entities SET status = 'needs_fact_review', verified = 0 WHERE id = 'khu-bao-ton-lung-binh-hoa-tra-vinh';

COMMIT;
